type IngredientCategory =
  | "PANTRY_STAPLE"
  | "CONDIMENT"
  | "OIL_FAT"
  | "GRAIN"
  | "LEGUME"
  | "NUT_SEED"
  | "BAKING";

type StorageType = "FRIDGE" | "FREEZER" | "PANTRY" | "COUNTER";

type FlavorTags = {
  sweet: number;
  spicy: number;
  umami: number;
  acidic: number;
  rich: number;
  light: number;
};

type CondimentSauceSeed = {
  name: string;
  category: IngredientCategory;
  defaultUnit: string;
  shelfLifeDays: number;
  storageType: StorageType;
  avgPricePerUnit: number;
  cuisineTags: string[];
  flavorTags: FlavorTags;
  description: string;
};

export const condimentsSauces: CondimentSauceSeed[] = [
  {
    name: "Red wine vinegar",
    category: "CONDIMENT",
    defaultUnit: "ml",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 0.008,
    cuisineTags: ["FRENCH", "ITALIAN", "MEDITERRANEAN"],
    flavorTags: { sweet: 0, spicy: 0, umami: 1, acidic: 9, rich: 1, light: 7 },
    description: "Aged wine vinegar for vinaigrettes, reductions, and deglazing.",
  },
  {
    name: "White wine vinegar",
    category: "CONDIMENT",
    defaultUnit: "ml",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 0.007,
    cuisineTags: ["FRENCH", "ITALIAN", "AMERICAN"],
    flavorTags: { sweet: 0, spicy: 0, umami: 0, acidic: 9, rich: 0, light: 8 },
    description: "Bright vinegar for pickles, sauces, and delicate dressings.",
  },
  {
    name: "Balsamic vinegar",
    category: "CONDIMENT",
    defaultUnit: "ml",
    shelfLifeDays: 1095,
    storageType: "PANTRY",
    avgPricePerUnit: 0.022,
    cuisineTags: ["ITALIAN", "MEDITERRANEAN"],
    flavorTags: { sweet: 5, spicy: 0, umami: 3, acidic: 6, rich: 6, light: 3 },
    description: "Sweet-tart aged grape must; drizzles, glazes, and finishing acidity.",
  },
  {
    name: "Sherry vinegar",
    category: "CONDIMENT",
    defaultUnit: "ml",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 0.018,
    cuisineTags: ["MEDITERRANEAN", "OTHER"],
    flavorTags: { sweet: 1, spicy: 0, umami: 3, acidic: 8, rich: 4, light: 5 },
    description: "Nutty aged sherry vinegar for gazpacho, sauces, and bold vinaigrettes.",
  },
  {
    name: "Rice vinegar",
    category: "CONDIMENT",
    defaultUnit: "ml",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 0.009,
    cuisineTags: ["JAPANESE", "CHINESE", "KOREAN"],
    flavorTags: { sweet: 2, spicy: 0, umami: 1, acidic: 7, rich: 1, light: 7 },
    description: "Mild vinegar for sushi rice, slaws, and Asian dipping sauces.",
  },
  {
    name: "Apple cider vinegar",
    category: "CONDIMENT",
    defaultUnit: "ml",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 0.007,
    cuisineTags: ["AMERICAN", "OTHER"],
    flavorTags: { sweet: 1, spicy: 0, umami: 0, acidic: 8, rich: 1, light: 7 },
    description: "Fruity vinegar for shrubs, dressings, and quick pickles.",
  },
  {
    name: "Champagne vinegar",
    category: "CONDIMENT",
    defaultUnit: "ml",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 0.014,
    cuisineTags: ["FRENCH", "AMERICAN"],
    flavorTags: { sweet: 0, spicy: 0, umami: 1, acidic: 8, rich: 1, light: 8 },
    description: "Delicate sparkling-wine vinegar for refined sauces and seafood dressings.",
  },
  {
    name: "Soy sauce",
    category: "CONDIMENT",
    defaultUnit: "ml",
    shelfLifeDays: 540,
    storageType: "PANTRY",
    avgPricePerUnit: 0.009,
    cuisineTags: ["CHINESE", "JAPANESE", "KOREAN", "THAI"],
    flavorTags: { sweet: 1, spicy: 0, umami: 9, acidic: 1, rich: 4, light: 4 },
    description: "Fermented wheat and soy salinity for marinades, stir-fries, and dipping.",
  },
  {
    name: "Fish sauce",
    category: "CONDIMENT",
    defaultUnit: "ml",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 0.011,
    cuisineTags: ["THAI", "SOUTHEAST_ASIAN"],
    flavorTags: { sweet: 0, spicy: 0, umami: 10, acidic: 1, rich: 5, light: 3 },
    description: "Anchovy-fermented umami bomb for curries, dressings, and savory depth.",
  },
  {
    name: "Worcestershire sauce",
    category: "CONDIMENT",
    defaultUnit: "ml",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 0.012,
    cuisineTags: ["AMERICAN", "OTHER"],
    flavorTags: { sweet: 2, spicy: 1, umami: 7, acidic: 4, rich: 5, light: 3 },
    description: "Complex tamarind-anchovy condiment for Caesar, burgers, and braises.",
  },
  {
    name: "Hot sauce (Louisiana-style)",
    category: "CONDIMENT",
    defaultUnit: "ml",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 0.015,
    cuisineTags: ["AMERICAN", "CARIBBEAN"],
    flavorTags: { sweet: 0, spicy: 8, umami: 2, acidic: 5, rich: 2, light: 5 },
    description: "Vinegar-forward cayenne heat for eggs, wings, and everyday finishing.",
  },
  {
    name: "Tabasco sauce",
    category: "CONDIMENT",
    defaultUnit: "ml",
    shelfLifeDays: 1825,
    storageType: "PANTRY",
    avgPricePerUnit: 0.028,
    cuisineTags: ["AMERICAN", "CARIBBEAN"],
    flavorTags: { sweet: 0, spicy: 7, umami: 2, acidic: 6, rich: 1, light: 5 },
    description: "Tabasco pepper mash and vinegar; classic dash heat.",
  },
  {
    name: "Sriracha",
    category: "CONDIMENT",
    defaultUnit: "ml",
    shelfLifeDays: 540,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.014,
    cuisineTags: ["THAI", "SOUTHEAST_ASIAN", "FUSION"],
    flavorTags: { sweet: 3, spicy: 7, umami: 3, acidic: 2, rich: 3, light: 4 },
    description: "Garlicky chili sauce for noodles, mayo blends, and sandwich kick.",
  },
  {
    name: "Sambal oelek",
    category: "CONDIMENT",
    defaultUnit: "g",
    shelfLifeDays: 365,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.018,
    cuisineTags: ["SOUTHEAST_ASIAN", "THAI"],
    flavorTags: { sweet: 1, spicy: 9, umami: 3, acidic: 2, rich: 2, light: 4 },
    description: "Raw chili paste with salt and vinegar; base heat for sambals and stir-fries.",
  },
  {
    name: "Tahini",
    category: "CONDIMENT",
    defaultUnit: "g",
    shelfLifeDays: 365,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.022,
    cuisineTags: ["MIDDLE_EASTERN", "MEDITERRANEAN"],
    flavorTags: { sweet: 0, spicy: 0, umami: 4, acidic: 0, rich: 7, light: 3 },
    description: "Sesame seed paste for hummus, dressings, and halva-style sweets.",
  },
  {
    name: "Harissa paste",
    category: "CONDIMENT",
    defaultUnit: "g",
    shelfLifeDays: 180,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.032,
    cuisineTags: ["MIDDLE_EASTERN", "AFRICAN", "MEDITERRANEAN"],
    flavorTags: { sweet: 1, spicy: 7, umami: 4, acidic: 2, rich: 5, light: 3 },
    description: "North African chili paste with caraway and coriander for rubs and stews.",
  },
  {
    name: "Tomato paste",
    category: "CONDIMENT",
    defaultUnit: "g",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 0.012,
    cuisineTags: ["ITALIAN", "MEDITERRANEAN", "AMERICAN"],
    flavorTags: { sweet: 2, spicy: 0, umami: 7, acidic: 4, rich: 5, light: 2 },
    description: "Concentrated tomato for sofrito, braises, and color depth.",
  },
  {
    name: "Dijon mustard",
    category: "CONDIMENT",
    defaultUnit: "g",
    shelfLifeDays: 365,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.025,
    cuisineTags: ["FRENCH", "AMERICAN"],
    flavorTags: { sweet: 0, spicy: 2, umami: 3, acidic: 5, rich: 3, light: 5 },
    description: "Smooth wine-forward mustard for vinaigrettes, crusts, and sandwiches.",
  },
  {
    name: "Whole grain mustard",
    category: "CONDIMENT",
    defaultUnit: "g",
    shelfLifeDays: 365,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.028,
    cuisineTags: ["FRENCH", "AMERICAN", "OTHER"],
    flavorTags: { sweet: 0, spicy: 3, umami: 3, acidic: 5, rich: 4, light: 4 },
    description: "Seedy mustard for charcuterie, roasts, and rustic sauces.",
  },
  {
    name: "Yellow mustard",
    category: "CONDIMENT",
    defaultUnit: "g",
    shelfLifeDays: 540,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.012,
    cuisineTags: ["AMERICAN", "DELI"],
    flavorTags: { sweet: 1, spicy: 2, umami: 2, acidic: 4, rich: 2, light: 6 },
    description: "Mild turmeric-tinted classic for dogs, burgers, and picnic tables.",
  },
  {
    name: "Mayonnaise",
    category: "CONDIMENT",
    defaultUnit: "g",
    shelfLifeDays: 90,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.018,
    cuisineTags: ["AMERICAN", "FRENCH", "DELI"],
    flavorTags: { sweet: 1, spicy: 0, umami: 2, acidic: 2, rich: 8, light: 2 },
    description: "Egg-emulsified spread for aioli bases, dressings, and sandwiches.",
  },
  {
    name: "Ketchup",
    category: "CONDIMENT",
    defaultUnit: "g",
    shelfLifeDays: 270,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.014,
    cuisineTags: ["AMERICAN", "OTHER"],
    flavorTags: { sweet: 6, spicy: 0, umami: 3, acidic: 4, rich: 3, light: 4 },
    description: "Tomato-sweet condiment for fries, meatloaf glazes, and BBQ tang.",
  },
  {
    name: "Extra virgin olive oil",
    category: "OIL_FAT",
    defaultUnit: "ml",
    shelfLifeDays: 540,
    storageType: "PANTRY",
    avgPricePerUnit: 0.018,
    cuisineTags: ["ITALIAN", "MEDITERRANEAN", "FRENCH"],
    flavorTags: { sweet: 0, spicy: 0, umami: 2, acidic: 0, rich: 7, light: 4 },
    description: "First-press oil for finishing, vinaigrettes, and gentle sautéing.",
  },
  {
    name: "Vegetable oil",
    category: "OIL_FAT",
    defaultUnit: "ml",
    shelfLifeDays: 540,
    storageType: "PANTRY",
    avgPricePerUnit: 0.006,
    cuisineTags: ["AMERICAN", "CHINESE", "INDIAN", "OTHER"],
    flavorTags: { sweet: 0, spicy: 0, umami: 0, acidic: 0, rich: 4, light: 6 },
    description: "Neutral high-heat oil for frying, baking, and all-purpose cooking.",
  },
  {
    name: "Canola oil",
    category: "OIL_FAT",
    defaultUnit: "ml",
    shelfLifeDays: 540,
    storageType: "PANTRY",
    avgPricePerUnit: 0.006,
    cuisineTags: ["AMERICAN", "OTHER"],
    flavorTags: { sweet: 0, spicy: 0, umami: 0, acidic: 0, rich: 3, light: 7 },
    description: "Light neutral oil with a high smoke point for everyday frying and cakes.",
  },
  {
    name: "Toasted sesame oil",
    category: "OIL_FAT",
    defaultUnit: "ml",
    shelfLifeDays: 365,
    storageType: "PANTRY",
    avgPricePerUnit: 0.028,
    cuisineTags: ["CHINESE", "JAPANESE", "KOREAN"],
    flavorTags: { sweet: 0, spicy: 0, umami: 6, acidic: 0, rich: 8, light: 2 },
    description: "Aromatic finishing oil for dumplings, noodles, and stir-fry bloom.",
  },
  {
    name: "Peanut oil",
    category: "OIL_FAT",
    defaultUnit: "ml",
    shelfLifeDays: 365,
    storageType: "PANTRY",
    avgPricePerUnit: 0.012,
    cuisineTags: ["CHINESE", "THAI", "AMERICAN"],
    flavorTags: { sweet: 0, spicy: 0, umami: 2, acidic: 0, rich: 6, light: 4 },
    description: "High smoke-point nutty oil ideal for deep frying and wok hei.",
  },
  {
    name: "Coconut oil (refined)",
    category: "OIL_FAT",
    defaultUnit: "g",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 0.018,
    cuisineTags: ["THAI", "SOUTHEAST_ASIAN", "INDIAN", "CARIBBEAN"],
    flavorTags: { sweet: 1, spicy: 0, umami: 1, acidic: 0, rich: 7, light: 3 },
    description: "Stable saturated fat for curries, popcorn, and high-heat searing.",
  },
  {
    name: "Walnut oil",
    category: "OIL_FAT",
    defaultUnit: "ml",
    shelfLifeDays: 180,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.045,
    cuisineTags: ["FRENCH", "AMERICAN", "OTHER"],
    flavorTags: { sweet: 1, spicy: 0, umami: 2, acidic: 0, rich: 7, light: 3 },
    description: "Nutty cold-press oil for salads and finishing; refrigerate after opening.",
  },
  {
    name: "Truffle oil (infused)",
    category: "OIL_FAT",
    defaultUnit: "ml",
    shelfLifeDays: 365,
    storageType: "PANTRY",
    avgPricePerUnit: 0.12,
    cuisineTags: ["ITALIAN", "FRENCH", "FUSION"],
    flavorTags: { sweet: 0, spicy: 0, umami: 8, acidic: 0, rich: 8, light: 1 },
    description: "Aromatic finishing oil for risotto, fries, and eggs—use sparingly.",
  },
  {
    name: "Lard (rendered)",
    category: "OIL_FAT",
    defaultUnit: "g",
    shelfLifeDays: 180,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.014,
    cuisineTags: ["MEXICAN", "AMERICAN", "CHINESE"],
    flavorTags: { sweet: 0, spicy: 0, umami: 3, acidic: 0, rich: 9, light: 1 },
    description: "Rendered pork fat for flaky pastry, confit, and traditional frying.",
  },
  {
    name: "Duck fat",
    category: "OIL_FAT",
    defaultUnit: "g",
    shelfLifeDays: 120,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.038,
    cuisineTags: ["FRENCH", "AMERICAN", "FUSION"],
    flavorTags: { sweet: 0, spicy: 0, umami: 5, acidic: 0, rich: 9, light: 1 },
    description: "Luxurious poultry fat for roasted potatoes, confit, and searing.",
  },
  {
    name: "Schmaltz (rendered chicken fat)",
    category: "OIL_FAT",
    defaultUnit: "g",
    shelfLifeDays: 90,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.032,
    cuisineTags: ["DELI", "MIDDLE_EASTERN", "AMERICAN"],
    flavorTags: { sweet: 0, spicy: 0, umami: 5, acidic: 0, rich: 8, light: 2 },
    description: "Rendered chicken fat with onion notes; matzo balls, latkes, and savory depth.",
  },
  {
    name: "White miso paste",
    category: "CONDIMENT",
    defaultUnit: "g",
    shelfLifeDays: 365,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.028,
    cuisineTags: ["JAPANESE"],
    flavorTags: { sweet: 3, spicy: 0, umami: 8, acidic: 1, rich: 4, light: 4 },
    description: "Mild sweet miso for soups, glazes, and light marinades.",
  },
  {
    name: "Red miso paste",
    category: "CONDIMENT",
    defaultUnit: "g",
    shelfLifeDays: 365,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.03,
    cuisineTags: ["JAPANESE"],
    flavorTags: { sweet: 2, spicy: 0, umami: 9, acidic: 1, rich: 6, light: 2 },
    description: "Longer-aged salty miso for bold braises, ramen tare, and marinades.",
  },
  {
    name: "Gochujang",
    category: "CONDIMENT",
    defaultUnit: "g",
    shelfLifeDays: 540,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.024,
    cuisineTags: ["KOREAN"],
    flavorTags: { sweet: 4, spicy: 6, umami: 7, acidic: 2, rich: 5, light: 2 },
    description: "Fermented chili-soy paste for bibimbap, wings, and sticky glazes.",
  },
  {
    name: "Thai red curry paste",
    category: "CONDIMENT",
    defaultUnit: "g",
    shelfLifeDays: 365,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.026,
    cuisineTags: ["THAI", "SOUTHEAST_ASIAN"],
    flavorTags: { sweet: 1, spicy: 7, umami: 5, acidic: 2, rich: 5, light: 3 },
    description: "Shrimp paste–aromatic red curry base with dried chiles and galangal.",
  },
  {
    name: "Thai green curry paste",
    category: "CONDIMENT",
    defaultUnit: "g",
    shelfLifeDays: 365,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.026,
    cuisineTags: ["THAI", "SOUTHEAST_ASIAN"],
    flavorTags: { sweet: 1, spicy: 6, umami: 5, acidic: 3, rich: 4, light: 5 },
    description: "Fresh green chile and herb paste for coconut curries and fast broths.",
  },
  {
    name: "Anchovy paste",
    category: "CONDIMENT",
    defaultUnit: "g",
    shelfLifeDays: 365,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.055,
    cuisineTags: ["ITALIAN", "FRENCH", "MEDITERRANEAN"],
    flavorTags: { sweet: 0, spicy: 0, umami: 9, acidic: 1, rich: 6, light: 2 },
    description: "Concentrated anchovy for Caesar, bagna cauda, and stealth umami.",
  },
  {
    name: "Capers (brined)",
    category: "CONDIMENT",
    defaultUnit: "g",
    shelfLifeDays: 540,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.04,
    cuisineTags: ["ITALIAN", "MEDITERRANEAN", "FRENCH"],
    flavorTags: { sweet: 0, spicy: 0, umami: 4, acidic: 7, rich: 2, light: 5 },
    description: "Briny flower buds for piccata, bagels, and bright finishing pops.",
  },
  {
    name: "Kalamata olives",
    category: "CONDIMENT",
    defaultUnit: "g",
    shelfLifeDays: 730,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.032,
    cuisineTags: ["MEDITERRANEAN"],
    flavorTags: { sweet: 0, spicy: 0, umami: 5, acidic: 4, rich: 5, light: 3 },
    description: "Purple Greek olives with winey tang for salads, tapenade, and mezze.",
  },
  {
    name: "Castelvetrano olives",
    category: "CONDIMENT",
    defaultUnit: "g",
    shelfLifeDays: 730,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.038,
    cuisineTags: ["ITALIAN", "MEDITERRANEAN"],
    flavorTags: { sweet: 2, spicy: 0, umami: 4, acidic: 2, rich: 4, light: 5 },
    description: "Buttery bright green Sicilian olives for snacking and mild olive notes.",
  },
];
