export type DairySeed = {
  name: string;
  category: "DAIRY";
  defaultUnit: string;
  shelfLifeDays: number;
  storageType: "FRIDGE" | "FREEZER" | "PANTRY" | "COUNTER";
  avgPricePerUnit: number;
  cuisineTags: string[];
  flavorTags: {
    sweet: number;
    spicy: number;
    umami: number;
    acidic: number;
    rich: number;
    light: number;
  };
  description: string;
};

export const dairy: DairySeed[] = [
  {
    name: "Whole milk",
    category: "DAIRY",
    defaultUnit: "ml",
    shelfLifeDays: 7,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.0011,
    cuisineTags: ["AMERICAN", "FRENCH", "ITALIAN", "OTHER"],
    flavorTags: { sweet: 3, spicy: 0, umami: 2, acidic: 1, rich: 4, light: 6 },
    description: "Full-fat cow’s milk for sauces, baking, coffee, and everyday cooking.",
  },
  {
    name: "Buttermilk",
    category: "DAIRY",
    defaultUnit: "ml",
    shelfLifeDays: 14,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.0014,
    cuisineTags: ["AMERICAN", "OTHER"],
    flavorTags: { sweet: 1, spicy: 0, umami: 2, acidic: 7, rich: 3, light: 5 },
    description: "Cultured low-fat milk with tangy flavor; ideal for fried chicken, pancakes, and ranch.",
  },
  {
    name: "Heavy cream",
    category: "DAIRY",
    defaultUnit: "ml",
    shelfLifeDays: 10,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.0032,
    cuisineTags: ["FRENCH", "ITALIAN", "AMERICAN", "OTHER"],
    flavorTags: { sweet: 2, spicy: 0, umami: 2, acidic: 0, rich: 10, light: 1 },
    description: "High-fat cream for whipping, ganache, soups, and silky pan sauces.",
  },
  {
    name: "Half-and-half",
    category: "DAIRY",
    defaultUnit: "ml",
    shelfLifeDays: 10,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.002,
    cuisineTags: ["AMERICAN", "OTHER"],
    flavorTags: { sweet: 2, spicy: 0, umami: 2, acidic: 1, rich: 6, light: 4 },
    description: "Equal parts milk and cream; common in coffee and lighter cream sauces.",
  },
  {
    name: "Coconut milk",
    category: "DAIRY",
    defaultUnit: "ml",
    shelfLifeDays: 5,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.0024,
    cuisineTags: ["INDIAN", "OTHER"],
    flavorTags: { sweet: 3, spicy: 0, umami: 2, acidic: 0, rich: 8, light: 3 },
    description: "Plant-based creamy liquid from coconut; curries, soups, and dairy-free desserts.",
  },
  {
    name: "Evaporated milk",
    category: "DAIRY",
    defaultUnit: "ml",
    shelfLifeDays: 5,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.002,
    cuisineTags: ["MEXICAN", "AMERICAN", "OTHER"],
    flavorTags: { sweet: 3, spicy: 0, umami: 3, acidic: 1, rich: 7, light: 2 },
    description: "Concentrated canned milk; flan, fudge, creamy sauces after opening refrigerate.",
  },
  {
    name: "Skim milk",
    category: "DAIRY",
    defaultUnit: "ml",
    shelfLifeDays: 7,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.001,
    cuisineTags: ["AMERICAN", "OTHER"],
    flavorTags: { sweet: 2, spicy: 0, umami: 1, acidic: 1, rich: 1, light: 9 },
    description: "Fat-free milk for lighter béchamel, smoothies, and everyday use.",
  },
  {
    name: "Kefir",
    category: "DAIRY",
    defaultUnit: "ml",
    shelfLifeDays: 21,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.0022,
    cuisineTags: ["MIDDLE_EASTERN", "OTHER"],
    flavorTags: { sweet: 2, spicy: 0, umami: 3, acidic: 6, rich: 4, light: 5 },
    description: "Fermented drinkable yogurt with probiotic tang; marinades and smoothies.",
  },
  {
    name: "Skyr",
    category: "DAIRY",
    defaultUnit: "g",
    shelfLifeDays: 14,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.022,
    cuisineTags: ["OTHER"],
    flavorTags: { sweet: 2, spicy: 0, umami: 4, acidic: 5, rich: 5, light: 5 },
    description: "Icelandic strained cultured dairy; thick like Greek yogurt, high protein.",
  },
  {
    name: "Parmesan cheese",
    category: "DAIRY",
    defaultUnit: "g",
    shelfLifeDays: 45,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.045,
    cuisineTags: ["ITALIAN", "AMERICAN", "OTHER"],
    flavorTags: { sweet: 1, spicy: 0, umami: 10, acidic: 2, rich: 7, light: 2 },
    description: "Aged hard cheese for grating over pasta, risotto, and salads.",
  },
  {
    name: "Fresh mozzarella",
    category: "DAIRY",
    defaultUnit: "g",
    shelfLifeDays: 5,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.028,
    cuisineTags: ["ITALIAN", "AMERICAN", "OTHER"],
    flavorTags: { sweet: 2, spicy: 0, umami: 5, acidic: 1, rich: 5, light: 6 },
    description: "Soft mild cheese for caprese, pizza, and sandwiches; keep in brine.",
  },
  {
    name: "Pecorino Romano",
    category: "DAIRY",
    defaultUnit: "g",
    shelfLifeDays: 60,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.042,
    cuisineTags: ["ITALIAN", "MEDITERRANEAN", "OTHER"],
    flavorTags: { sweet: 0, spicy: 0, umami: 9, acidic: 4, rich: 6, light: 2 },
    description: "Salty sheep’s milk cheese; classic with cacio e pepe and Roman dishes.",
  },
  {
    name: "Gruyère cheese",
    category: "DAIRY",
    defaultUnit: "g",
    shelfLifeDays: 30,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.052,
    cuisineTags: ["FRENCH", "OTHER"],
    flavorTags: { sweet: 2, spicy: 0, umami: 8, acidic: 1, rich: 8, light: 2 },
    description: "Nutty melting cheese for fondue, French onion soup, and gratins.",
  },
  {
    name: "Cheddar cheese",
    category: "DAIRY",
    defaultUnit: "g",
    shelfLifeDays: 21,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.018,
    cuisineTags: ["AMERICAN", "OTHER"],
    flavorTags: { sweet: 1, spicy: 0, umami: 7, acidic: 2, rich: 6, light: 3 },
    description: "Sharp or mild aged cow’s milk cheese; melting, snacking, and mac and cheese.",
  },
  {
    name: "Cream cheese",
    category: "DAIRY",
    defaultUnit: "g",
    shelfLifeDays: 14,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.012,
    cuisineTags: ["AMERICAN", "DELI", "OTHER"],
    flavorTags: { sweet: 3, spicy: 0, umami: 3, acidic: 2, rich: 8, light: 2 },
    description: "Spreadable fresh cheese for bagels, frostings, and creamy dips.",
  },
  {
    name: "Ricotta cheese",
    category: "DAIRY",
    defaultUnit: "g",
    shelfLifeDays: 7,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.014,
    cuisineTags: ["ITALIAN", "AMERICAN", "OTHER"],
    flavorTags: { sweet: 3, spicy: 0, umami: 4, acidic: 2, rich: 5, light: 6 },
    description: "Mild whey cheese for lasagna, cannoli filling, and light spreads.",
  },
  {
    name: "Mascarpone",
    category: "DAIRY",
    defaultUnit: "g",
    shelfLifeDays: 7,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.035,
    cuisineTags: ["ITALIAN", "FRENCH", "OTHER"],
    flavorTags: { sweet: 4, spicy: 0, umami: 3, acidic: 1, rich: 10, light: 2 },
    description: "Rich Italian cream cheese; tiramisu, frostings, and creamy sauces.",
  },
  {
    name: "Goat cheese (chèvre)",
    category: "DAIRY",
    defaultUnit: "g",
    shelfLifeDays: 10,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.055,
    cuisineTags: ["FRENCH", "MEDITERRANEAN", "AMERICAN", "OTHER"],
    flavorTags: { sweet: 2, spicy: 0, umami: 4, acidic: 5, rich: 5, light: 5 },
    description: "Tangy soft cheese for salads, tarts, and spreads.",
  },
  {
    name: "Feta cheese",
    category: "DAIRY",
    defaultUnit: "g",
    shelfLifeDays: 14,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.022,
    cuisineTags: ["MEDITERRANEAN", "MIDDLE_EASTERN", "OTHER"],
    flavorTags: { sweet: 1, spicy: 0, umami: 6, acidic: 7, rich: 4, light: 5 },
    description: "Brined sheep or mixed milk cheese; Greek salad, spanakopita, and grain bowls.",
  },
  {
    name: "Cotija cheese",
    category: "DAIRY",
    defaultUnit: "g",
    shelfLifeDays: 30,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.032,
    cuisineTags: ["MEXICAN", "AMERICAN", "OTHER"],
    flavorTags: { sweet: 0, spicy: 0, umami: 8, acidic: 3, rich: 5, light: 3 },
    description: "Crumbly salty Mexican cheese for elote, tacos, and beans.",
  },
  {
    name: "Queso fresco",
    category: "DAIRY",
    defaultUnit: "g",
    shelfLifeDays: 10,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.018,
    cuisineTags: ["MEXICAN", "OTHER"],
    flavorTags: { sweet: 2, spicy: 0, umami: 4, acidic: 3, rich: 3, light: 6 },
    description: "Mild fresh crumbling cheese for enchiladas, salads, and sopes.",
  },
  {
    name: "Blue cheese",
    category: "DAIRY",
    defaultUnit: "g",
    shelfLifeDays: 21,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.048,
    cuisineTags: ["FRENCH", "ITALIAN", "AMERICAN", "OTHER"],
    flavorTags: { sweet: 1, spicy: 0, umami: 9, acidic: 5, rich: 8, light: 2 },
    description: "Veined mold-ripened cheese with bold funk; dressings, steaks, and cheese boards.",
  },
  {
    name: "Brie",
    category: "DAIRY",
    defaultUnit: "g",
    shelfLifeDays: 14,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.038,
    cuisineTags: ["FRENCH", "AMERICAN", "OTHER"],
    flavorTags: { sweet: 3, spicy: 0, umami: 5, acidic: 2, rich: 9, light: 3 },
    description: "Soft-ripened bloomy rind cheese; baked brie, sandwiches, and platters.",
  },
  {
    name: "Swiss cheese",
    category: "DAIRY",
    defaultUnit: "g",
    shelfLifeDays: 21,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.02,
    cuisineTags: ["DELI", "AMERICAN", "OTHER"],
    flavorTags: { sweet: 2, spicy: 0, umami: 6, acidic: 1, rich: 5, light: 4 },
    description: "Mild nutty melting cheese for Reubens, fondue, and layered sandwiches.",
  },
  {
    name: "Paneer",
    category: "DAIRY",
    defaultUnit: "g",
    shelfLifeDays: 5,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.025,
    cuisineTags: ["INDIAN", "OTHER"],
    flavorTags: { sweet: 1, spicy: 0, umami: 4, acidic: 1, rich: 4, light: 6 },
    description: "Fresh acid-set cheese that holds shape when cooked; paneer tikka and palak paneer.",
  },
  {
    name: "Unsalted butter",
    category: "DAIRY",
    defaultUnit: "g",
    shelfLifeDays: 60,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.014,
    cuisineTags: ["FRENCH", "ITALIAN", "AMERICAN", "OTHER"],
    flavorTags: { sweet: 2, spicy: 0, umami: 2, acidic: 0, rich: 9, light: 2 },
    description: "Sweet cream butter for baking and sauces where salt is controlled separately.",
  },
  {
    name: "Salted butter",
    category: "DAIRY",
    defaultUnit: "g",
    shelfLifeDays: 60,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.013,
    cuisineTags: ["AMERICAN", "FRENCH", "OTHER"],
    flavorTags: { sweet: 1, spicy: 0, umami: 5, acidic: 0, rich: 8, light: 2 },
    description: "Table and cooking butter with salt for spreadability and savory depth.",
  },
  {
    name: "Ghee",
    category: "DAIRY",
    defaultUnit: "g",
    shelfLifeDays: 90,
    storageType: "PANTRY",
    avgPricePerUnit: 0.028,
    cuisineTags: ["INDIAN", "MIDDLE_EASTERN", "OTHER"],
    flavorTags: { sweet: 1, spicy: 0, umami: 4, acidic: 0, rich: 10, light: 1 },
    description: "Clarified butter with milk solids removed; high-smoke frying and aromatic rice.",
  },
  {
    name: "Greek yogurt",
    category: "DAIRY",
    defaultUnit: "g",
    shelfLifeDays: 14,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.011,
    cuisineTags: ["MEDITERRANEAN", "MIDDLE_EASTERN", "AMERICAN", "OTHER"],
    flavorTags: { sweet: 2, spicy: 0, umami: 4, acidic: 6, rich: 5, light: 5 },
    description: "Strained thick yogurt; tzatziki, marinades, and breakfast parfaits.",
  },
  {
    name: "Plain yogurt",
    category: "DAIRY",
    defaultUnit: "g",
    shelfLifeDays: 14,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.008,
    cuisineTags: ["INDIAN", "MIDDLE_EASTERN", "AMERICAN", "OTHER"],
    flavorTags: { sweet: 3, spicy: 0, umami: 3, acidic: 5, rich: 3, light: 6 },
    description: "Whole or low-fat cultured milk; raita, smoothies, and tenderizing marinades.",
  },
  {
    name: "Sour cream",
    category: "DAIRY",
    defaultUnit: "g",
    shelfLifeDays: 14,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.009,
    cuisineTags: ["MEXICAN", "AMERICAN", "OTHER"],
    flavorTags: { sweet: 2, spicy: 0, umami: 3, acidic: 5, rich: 6, light: 4 },
    description: "Cultured cream topping for tacos, baked potatoes, and stroganoff.",
  },
  {
    name: "Crème fraîche",
    category: "DAIRY",
    defaultUnit: "g",
    shelfLifeDays: 14,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.024,
    cuisineTags: ["FRENCH", "OTHER"],
    flavorTags: { sweet: 2, spicy: 0, umami: 4, acidic: 4, rich: 9, light: 3 },
    description: "Rich cultured cream that won’t break when simmered; finish sauces and soups.",
  },
];
