type IngredientCategory =
  | "PANTRY_STAPLE"
  | "CONDIMENT"
  | "OIL_FAT"
  | "GRAIN"
  | "LEGUME"
  | "NUT_SEED"
  | "BAKING";

type StorageType = "FRIDGE" | "FREEZER" | "PANTRY" | "COUNTER";

type FlavorTags = {
  sweet: number;
  spicy: number;
  umami: number;
  acidic: number;
  rich: number;
  light: number;
};

type GrainLegumeSeed = {
  name: string;
  category: IngredientCategory;
  defaultUnit: string;
  shelfLifeDays: number;
  storageType: StorageType;
  avgPricePerUnit: number;
  cuisineTags: string[];
  flavorTags: FlavorTags;
  description: string;
};

export const grainsLegumes: GrainLegumeSeed[] = [
  {
    name: "Arborio rice",
    category: "GRAIN",
    defaultUnit: "kg",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 4.2,
    cuisineTags: ["ITALIAN"],
    flavorTags: { sweet: 1, spicy: 0, umami: 2, acidic: 0, rich: 3, light: 5 },
    description: "Short starchy rice for creamy risotto and arancini.",
  },
  {
    name: "Basmati rice",
    category: "GRAIN",
    defaultUnit: "kg",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 3.6,
    cuisineTags: ["INDIAN", "MIDDLE_EASTERN"],
    flavorTags: { sweet: 1, spicy: 0, umami: 1, acidic: 0, rich: 2, light: 6 },
    description: "Aromatic long-grain rice for biryanis, pilafs, and pairing with curries.",
  },
  {
    name: "Jasmine rice",
    category: "GRAIN",
    defaultUnit: "kg",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 3.2,
    cuisineTags: ["THAI", "SOUTHEAST_ASIAN"],
    flavorTags: { sweet: 1, spicy: 0, umami: 1, acidic: 0, rich: 2, light: 6 },
    description: "Floral Thai staple for stir-fries, larb, and coconut curries.",
  },
  {
    name: "Sushi rice (short grain)",
    category: "GRAIN",
    defaultUnit: "kg",
    shelfLifeDays: 365,
    storageType: "PANTRY",
    avgPricePerUnit: 3.8,
    cuisineTags: ["JAPANESE", "KOREAN"],
    flavorTags: { sweet: 1, spicy: 0, umami: 2, acidic: 1, rich: 2, light: 5 },
    description: "Sticky polished rice seasoned for nigiri, rolls, and rice bowls.",
  },
  {
    name: "Wild rice blend",
    category: "GRAIN",
    defaultUnit: "kg",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 12.0,
    cuisineTags: ["AMERICAN", "FUSION"],
    flavorTags: { sweet: 0, spicy: 0, umami: 3, acidic: 0, rich: 4, light: 4 },
    description: "Nutty aquatic grass seed; pilafs, stuffings, and hearty salads.",
  },
  {
    name: "Spaghetti (dried)",
    category: "GRAIN",
    defaultUnit: "kg",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 2.8,
    cuisineTags: ["ITALIAN", "AMERICAN"],
    flavorTags: { sweet: 0, spicy: 0, umami: 2, acidic: 0, rich: 2, light: 5 },
    description: "Long round pasta for cacio e pepe, amatriciana, and classic red sauce.",
  },
  {
    name: "Penne rigate (dried)",
    category: "GRAIN",
    defaultUnit: "kg",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 2.6,
    cuisineTags: ["ITALIAN", "AMERICAN"],
    flavorTags: { sweet: 0, spicy: 0, umami: 2, acidic: 0, rich: 2, light: 5 },
    description: "Ridged tubes that hold chunky sauces and baked pasta dishes.",
  },
  {
    name: "Linguine (dried)",
    category: "GRAIN",
    defaultUnit: "kg",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 2.9,
    cuisineTags: ["ITALIAN"],
    flavorTags: { sweet: 0, spicy: 0, umami: 2, acidic: 0, rich: 2, light: 5 },
    description: "Flat strands for vongole, pesto, and light seafood sauces.",
  },
  {
    name: "Rigatoni (dried)",
    category: "GRAIN",
    defaultUnit: "kg",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 2.7,
    cuisineTags: ["ITALIAN", "AMERICAN"],
    flavorTags: { sweet: 0, spicy: 0, umami: 2, acidic: 0, rich: 3, light: 4 },
    description: "Large tubes for ragù, baked ziti-style bakes, and chunky sauces.",
  },
  {
    name: "Egg noodles (dried)",
    category: "GRAIN",
    defaultUnit: "kg",
    shelfLifeDays: 540,
    storageType: "PANTRY",
    avgPricePerUnit: 3.4,
    cuisineTags: ["AMERICAN", "DELI", "CHINESE"],
    flavorTags: { sweet: 0, spicy: 0, umami: 2, acidic: 0, rich: 4, light: 4 },
    description: "Rich yolk noodles for stroganoff, soups, and lo mein-style dishes.",
  },
  {
    name: "Orzo",
    category: "GRAIN",
    defaultUnit: "kg",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 4.0,
    cuisineTags: ["ITALIAN", "MEDITERRANEAN", "MIDDLE_EASTERN"],
    flavorTags: { sweet: 0, spicy: 0, umami: 2, acidic: 0, rich: 2, light: 5 },
    description: "Rice-shaped pasta for pilaf-style sides, soups, and salads.",
  },
  {
    name: "Sourdough loaf",
    category: "GRAIN",
    defaultUnit: "count",
    shelfLifeDays: 4,
    storageType: "COUNTER",
    avgPricePerUnit: 6.5,
    cuisineTags: ["AMERICAN", "FRENCH", "FUSION"],
    flavorTags: { sweet: 1, spicy: 0, umami: 3, acidic: 3, rich: 3, light: 4 },
    description: "Naturally leavened crusty bread for toast, sandwiches, and bread crumbs.",
  },
  {
    name: "Baguette",
    category: "GRAIN",
    defaultUnit: "count",
    shelfLifeDays: 2,
    storageType: "COUNTER",
    avgPricePerUnit: 3.2,
    cuisineTags: ["FRENCH", "SOUTHEAST_ASIAN"],
    flavorTags: { sweet: 1, spicy: 0, umami: 2, acidic: 0, rich: 2, light: 6 },
    description: "Crisp-crusted French loaf for tartines, banh mi, and garlic bread.",
  },
  {
    name: "Ciabatta",
    category: "GRAIN",
    defaultUnit: "count",
    shelfLifeDays: 3,
    storageType: "COUNTER",
    avgPricePerUnit: 4.0,
    cuisineTags: ["ITALIAN", "AMERICAN"],
    flavorTags: { sweet: 1, spicy: 0, umami: 2, acidic: 0, rich: 3, light: 5 },
    description: "Open-crumb Italian slipper bread for panini and olive oil dipping.",
  },
  {
    name: "Rye bread",
    category: "GRAIN",
    defaultUnit: "count",
    shelfLifeDays: 5,
    storageType: "COUNTER",
    avgPricePerUnit: 5.5,
    cuisineTags: ["DELI", "MIDDLE_EASTERN", "OTHER"],
    flavorTags: { sweet: 1, spicy: 0, umami: 3, acidic: 1, rich: 4, light: 3 },
    description: "Caraway-forward dense loaf for pastrami, smørrebrød, and toast.",
  },
  {
    name: "Flour tortillas (8-inch)",
    category: "GRAIN",
    defaultUnit: "count",
    shelfLifeDays: 14,
    storageType: "PANTRY",
    avgPricePerUnit: 0.22,
    cuisineTags: ["MEXICAN", "AMERICAN"],
    flavorTags: { sweet: 1, spicy: 0, umami: 2, acidic: 0, rich: 3, light: 5 },
    description: "Soft wheat wraps for tacos, quesadillas, and burritos.",
  },
  {
    name: "Corn tortillas (6-inch)",
    category: "GRAIN",
    defaultUnit: "count",
    shelfLifeDays: 10,
    storageType: "PANTRY",
    avgPricePerUnit: 0.14,
    cuisineTags: ["MEXICAN"],
    flavorTags: { sweet: 0, spicy: 0, umami: 3, acidic: 0, rich: 2, light: 6 },
    description: "Nixtamal corn disks for tacos, enchiladas, and tostadas.",
  },
  {
    name: "Black beans (dried)",
    category: "LEGUME",
    defaultUnit: "kg",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 3.8,
    cuisineTags: ["MEXICAN", "CARIBBEAN", "AMERICAN"],
    flavorTags: { sweet: 0, spicy: 0, umami: 4, acidic: 0, rich: 3, light: 4 },
    description: "Earthy legume for rice and beans, soups, and vegetarian fillings.",
  },
  {
    name: "Pinto beans (dried)",
    category: "LEGUME",
    defaultUnit: "kg",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 3.2,
    cuisineTags: ["MEXICAN", "AMERICAN"],
    flavorTags: { sweet: 1, spicy: 0, umami: 4, acidic: 0, rich: 3, light: 4 },
    description: "Creamy Southwest staple for refried beans, chili, and burritos.",
  },
  {
    name: "Cannellini beans (dried)",
    category: "LEGUME",
    defaultUnit: "kg",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 4.0,
    cuisineTags: ["ITALIAN", "MEDITERRANEAN"],
    flavorTags: { sweet: 0, spicy: 0, umami: 4, acidic: 0, rich: 3, light: 5 },
    description: "Large white kidney beans for minestrone, tuscan salads, and purées.",
  },
  {
    name: "Chickpeas (dried)",
    category: "LEGUME",
    defaultUnit: "kg",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 3.5,
    cuisineTags: ["MIDDLE_EASTERN", "INDIAN", "MEDITERRANEAN"],
    flavorTags: { sweet: 1, spicy: 0, umami: 4, acidic: 0, rich: 3, light: 4 },
    description: "Versatile garbanzos for hummus, chana masala, and crispy roasting.",
  },
  {
    name: "Red lentils (dried)",
    category: "LEGUME",
    defaultUnit: "kg",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 4.2,
    cuisineTags: ["INDIAN", "MIDDLE_EASTERN"],
    flavorTags: { sweet: 1, spicy: 0, umami: 3, acidic: 0, rich: 3, light: 5 },
    description: "Quick-cooking split lentils for dal, soups, and pureed sides.",
  },
  {
    name: "Green lentils (dried)",
    category: "LEGUME",
    defaultUnit: "kg",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 4.5,
    cuisineTags: ["FRENCH", "MEDITERRANEAN", "INDIAN"],
    flavorTags: { sweet: 0, spicy: 0, umami: 4, acidic: 0, rich: 3, light: 4 },
    description: "Firm peppery lentils that hold shape for salads and braises.",
  },
  {
    name: "Couscous (medium)",
    category: "GRAIN",
    defaultUnit: "kg",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 5.0,
    cuisineTags: ["MIDDLE_EASTERN", "MEDITERRANEAN", "AFRICAN"],
    flavorTags: { sweet: 0, spicy: 0, umami: 2, acidic: 0, rich: 2, light: 6 },
    description: "Steamed semolina granules for tagines, salads, and quick sides.",
  },
  {
    name: "Polenta (coarse)",
    category: "GRAIN",
    defaultUnit: "kg",
    shelfLifeDays: 365,
    storageType: "PANTRY",
    avgPricePerUnit: 3.8,
    cuisineTags: ["ITALIAN", "AMERICAN"],
    flavorTags: { sweet: 1, spicy: 0, umami: 2, acidic: 0, rich: 4, light: 4 },
    description: "Cornmeal porridge base for creamy sides, grilled cakes, and braise beds.",
  },
  {
    name: "Quinoa",
    category: "GRAIN",
    defaultUnit: "kg",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 8.5,
    cuisineTags: ["FUSION", "AMERICAN", "OTHER"],
    flavorTags: { sweet: 0, spicy: 0, umami: 2, acidic: 0, rich: 2, light: 6 },
    description: "Protein-rich pseudograin for bowls, salads, and stuffing.",
  },
  {
    name: "Farro",
    category: "GRAIN",
    defaultUnit: "kg",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 7.2,
    cuisineTags: ["ITALIAN", "MEDITERRANEAN"],
    flavorTags: { sweet: 0, spicy: 0, umami: 3, acidic: 0, rich: 3, light: 5 },
    description: "Chewy ancient wheat berry for grain salads, risotto-style dishes, and soups.",
  },
  {
    name: "Bulgur wheat",
    category: "GRAIN",
    defaultUnit: "kg",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 4.8,
    cuisineTags: ["MIDDLE_EASTERN", "MEDITERRANEAN"],
    flavorTags: { sweet: 0, spicy: 0, umami: 2, acidic: 0, rich: 2, light: 6 },
    description: "Parcooked cracked wheat for tabbouleh, kibbeh, and pilafs.",
  },
  {
    name: "Panko breadcrumbs",
    category: "GRAIN",
    defaultUnit: "g",
    shelfLifeDays: 365,
    storageType: "PANTRY",
    avgPricePerUnit: 0.018,
    cuisineTags: ["JAPANESE", "AMERICAN", "FUSION"],
    flavorTags: { sweet: 0, spicy: 0, umami: 2, acidic: 0, rich: 3, light: 6 },
    description: "Flaky Japanese crumbs for extra-crisp katsu, casseroles, and crusts.",
  },
];
