export type HerbSeed = {
  name: string;
  category: "HERB";
  defaultUnit: string;
  shelfLifeDays: number;
  storageType: "FRIDGE" | "FREEZER" | "PANTRY" | "COUNTER";
  avgPricePerUnit: number;
  cuisineTags: string[];
  flavorTags: {
    sweet: number;
    spicy: number;
    umami: number;
    acidic: number;
    rich: number;
    light: number;
  };
  description: string;
};

export const herbs: HerbSeed[] = [
  {
    name: "Basil (sweet)",
    category: "HERB",
    defaultUnit: "bunch",
    shelfLifeDays: 7,
    storageType: "FRIDGE",
    avgPricePerUnit: 2.49,
    cuisineTags: ["ITALIAN", "MEDITERRANEAN", "AMERICAN", "OTHER"],
    flavorTags: { sweet: 3, spicy: 0, umami: 2, acidic: 1, rich: 2, light: 7 },
    description: "Anise-sweet leaves for pesto, caprese, and Thai-inspired dishes when paired with heat.",
  },
  {
    name: "Flat-leaf parsley",
    category: "HERB",
    defaultUnit: "bunch",
    shelfLifeDays: 10,
    storageType: "FRIDGE",
    avgPricePerUnit: 1.79,
    cuisineTags: ["ITALIAN", "FRENCH", "MEDITERRANEAN", "MIDDLE_EASTERN", "AMERICAN", "OTHER"],
    flavorTags: { sweet: 1, spicy: 0, umami: 2, acidic: 2, rich: 1, light: 8 },
    description: "Bright grassy garnish and salad herb; holds up better than curly in cooking.",
  },
  {
    name: "Curly parsley",
    category: "HERB",
    defaultUnit: "bunch",
    shelfLifeDays: 10,
    storageType: "FRIDGE",
    avgPricePerUnit: 1.69,
    cuisineTags: ["AMERICAN", "DELI", "OTHER"],
    flavorTags: { sweet: 1, spicy: 0, umami: 1, acidic: 2, rich: 1, light: 8 },
    description: "Decorative mild parsley for platters, tabbouleh texture, and classic garnish.",
  },
  {
    name: "Cilantro",
    category: "HERB",
    defaultUnit: "bunch",
    shelfLifeDays: 7,
    storageType: "FRIDGE",
    avgPricePerUnit: 1.29,
    cuisineTags: ["MEXICAN", "MIDDLE_EASTERN", "INDIAN", "OTHER"],
    flavorTags: { sweet: 1, spicy: 1, umami: 2, acidic: 3, rich: 1, light: 7 },
    description: "Citrus-pungent leaves and stems; salsas, pho, and chutneys.",
  },
  {
    name: "Dill (fresh)",
    category: "HERB",
    defaultUnit: "bunch",
    shelfLifeDays: 7,
    storageType: "FRIDGE",
    avgPricePerUnit: 2.19,
    cuisineTags: ["DELI", "MEDITERRANEAN", "OTHER"],
    flavorTags: { sweet: 1, spicy: 0, umami: 2, acidic: 2, rich: 2, light: 7 },
    description: "Feathery fronds for gravlax, yogurt sauces, and new potatoes.",
  },
  {
    name: "Mint (fresh)",
    category: "HERB",
    defaultUnit: "bunch",
    shelfLifeDays: 8,
    storageType: "FRIDGE",
    avgPricePerUnit: 2.29,
    cuisineTags: ["MIDDLE_EASTERN", "MEDITERRANEAN", "INDIAN", "OTHER"],
    flavorTags: { sweet: 3, spicy: 1, umami: 1, acidic: 2, rich: 1, light: 8 },
    description: "Cooling aromatic; tea, lamb, salads, and Southeast Asian salads when needed.",
  },
  {
    name: "Rosemary (fresh)",
    category: "HERB",
    defaultUnit: "bunch",
    shelfLifeDays: 10,
    storageType: "FRIDGE",
    avgPricePerUnit: 2.99,
    cuisineTags: ["ITALIAN", "MEDITERRANEAN", "FRENCH", "AMERICAN", "OTHER"],
    flavorTags: { sweet: 0, spicy: 1, umami: 3, acidic: 1, rich: 4, light: 4 },
    description: "Piney woody sprigs; roast lamb, focaccia, and potato wedges.",
  },
  {
    name: "Thyme (fresh)",
    category: "HERB",
    defaultUnit: "bunch",
    shelfLifeDays: 10,
    storageType: "FRIDGE",
    avgPricePerUnit: 2.49,
    cuisineTags: ["FRENCH", "ITALIAN", "MEDITERRANEAN", "AMERICAN", "OTHER"],
    flavorTags: { sweet: 0, spicy: 0, umami: 3, acidic: 1, rich: 3, light: 5 },
    description: "Earthy small leaves; mirepoix, poultry, and mushroom dishes.",
  },
  {
    name: "Sage (fresh)",
    category: "HERB",
    defaultUnit: "bunch",
    shelfLifeDays: 8,
    storageType: "FRIDGE",
    avgPricePerUnit: 2.79,
    cuisineTags: ["ITALIAN", "AMERICAN", "OTHER"],
    flavorTags: { sweet: 0, spicy: 0, umami: 4, acidic: 0, rich: 5, light: 3 },
    description: "Savory fuzzy leaves; brown butter sauce, pork, and Thanksgiving stuffing.",
  },
  {
    name: "Oregano (fresh)",
    category: "HERB",
    defaultUnit: "bunch",
    shelfLifeDays: 7,
    storageType: "FRIDGE",
    avgPricePerUnit: 2.19,
    cuisineTags: ["ITALIAN", "MEXICAN", "MEDITERRANEAN", "AMERICAN", "OTHER"],
    flavorTags: { sweet: 0, spicy: 2, umami: 3, acidic: 2, rich: 2, light: 5 },
    description: "Bold peppery green; finish pizzas, beans, and Greek salads.",
  },
  {
    name: "Tarragon (fresh)",
    category: "HERB",
    defaultUnit: "bunch",
    shelfLifeDays: 6,
    storageType: "FRIDGE",
    avgPricePerUnit: 3.29,
    cuisineTags: ["FRENCH", "OTHER"],
    flavorTags: { sweet: 1, spicy: 0, umami: 2, acidic: 2, rich: 2, light: 6 },
    description: "French tarragon anise note; chicken, béarnaise, and fines herbes.",
  },
  {
    name: "Chives (fresh)",
    category: "HERB",
    defaultUnit: "bunch",
    shelfLifeDays: 7,
    storageType: "FRIDGE",
    avgPricePerUnit: 2.09,
    cuisineTags: ["FRENCH", "DELI", "AMERICAN", "OTHER"],
    flavorTags: { sweet: 1, spicy: 0, umami: 3, acidic: 1, rich: 2, light: 7 },
    description: "Mild onion grass; potatoes, crème fraîche dips, and omelets.",
  },
  {
    name: "Bay leaf (fresh)",
    category: "HERB",
    defaultUnit: "g",
    shelfLifeDays: 10,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.08,
    cuisineTags: ["FRENCH", "ITALIAN", "MEXICAN", "OTHER"],
    flavorTags: { sweet: 0, spicy: 0, umami: 3, acidic: 1, rich: 3, light: 4 },
    description: "Milder than dried; stocks, braises, and rice pilaf—remove before serving.",
  },
  {
    name: "Lemongrass (fresh)",
    category: "HERB",
    defaultUnit: "g",
    shelfLifeDays: 10,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.025,
    cuisineTags: ["OTHER"],
    flavorTags: { sweet: 2, spicy: 1, umami: 2, acidic: 4, rich: 1, light: 7 },
    description: "Citrus stalk for bruising into curries, broths, and lemongrass paste.",
  },
  {
    name: "Epazote (fresh)",
    category: "HERB",
    defaultUnit: "bunch",
    shelfLifeDays: 5,
    storageType: "FRIDGE",
    avgPricePerUnit: 2.99,
    cuisineTags: ["MEXICAN", "OTHER"],
    flavorTags: { sweet: 0, spicy: 1, umami: 3, acidic: 4, rich: 2, light: 6 },
    description: "Pungent Mexican herb; black beans, quesadillas, and traditional moles.",
  },
  {
    name: "Marjoram (fresh)",
    category: "HERB",
    defaultUnit: "bunch",
    shelfLifeDays: 7,
    storageType: "FRIDGE",
    avgPricePerUnit: 2.59,
    cuisineTags: ["MEDITERRANEAN", "ITALIAN", "FRENCH", "OTHER"],
    flavorTags: { sweet: 2, spicy: 0, umami: 2, acidic: 1, rich: 2, light: 7 },
    description: "Sweeter softer cousin to oregano; vegetables, sausage, and herb butter.",
  },
  {
    name: "Lavender (culinary, fresh)",
    category: "HERB",
    defaultUnit: "g",
    shelfLifeDays: 7,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.12,
    cuisineTags: ["FRENCH", "MEDITERRANEAN", "OTHER"],
    flavorTags: { sweet: 3, spicy: 0, umami: 1, acidic: 1, rich: 2, light: 6 },
    description: "Floral buds used sparingly; honey, roast chicken, and desserts.",
  },
  {
    name: "Chervil (fresh)",
    category: "HERB",
    defaultUnit: "bunch",
    shelfLifeDays: 5,
    storageType: "FRIDGE",
    avgPricePerUnit: 3.49,
    cuisineTags: ["FRENCH", "OTHER"],
    flavorTags: { sweet: 1, spicy: 0, umami: 2, acidic: 2, rich: 1, light: 8 },
    description: "Delicate parsley-anise; fines herbes, eggs, and light cream sauces.",
  },
  {
    name: "Thai basil",
    category: "HERB",
    defaultUnit: "bunch",
    shelfLifeDays: 7,
    storageType: "FRIDGE",
    avgPricePerUnit: 2.79,
    cuisineTags: ["OTHER"],
    flavorTags: { sweet: 2, spicy: 2, umami: 3, acidic: 1, rich: 2, light: 6 },
    description: "Licorice-basil punch; stir-fries, larb, and pho garnish.",
  },
  {
    name: "Lemon balm (fresh)",
    category: "HERB",
    defaultUnit: "bunch",
    shelfLifeDays: 6,
    storageType: "FRIDGE",
    avgPricePerUnit: 2.39,
    cuisineTags: ["MEDITERRANEAN", "MIDDLE_EASTERN", "OTHER"],
    flavorTags: { sweet: 3, spicy: 0, umami: 1, acidic: 3, rich: 1, light: 8 },
    description: "Citrus-mint calm flavor; tea, fruit salads, and fish marinades.",
  },
  {
    name: "Sorrel (fresh)",
    category: "HERB",
    defaultUnit: "g",
    shelfLifeDays: 5,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.04,
    cuisineTags: ["FRENCH", "OTHER"],
    flavorTags: { sweet: 1, spicy: 0, umami: 2, acidic: 8, rich: 2, light: 6 },
    description: "Sour lemony leaf; soup, sauce verte, and salmon pairings.",
  },
];
