type IngredientCategory =
  | "PANTRY_STAPLE"
  | "CONDIMENT"
  | "OIL_FAT"
  | "GRAIN"
  | "LEGUME"
  | "NUT_SEED"
  | "BAKING";

type StorageType = "FRIDGE" | "FREEZER" | "PANTRY" | "COUNTER";

type FlavorTags = {
  sweet: number;
  spicy: number;
  umami: number;
  acidic: number;
  rich: number;
  light: number;
};

type PantryStapleSeed = {
  name: string;
  category: IngredientCategory;
  defaultUnit: string;
  shelfLifeDays: number;
  storageType: StorageType;
  avgPricePerUnit: number;
  cuisineTags: string[];
  flavorTags: FlavorTags;
  description: string;
};

export const pantryStaples: PantryStapleSeed[] = [
  {
    name: "All-purpose flour",
    category: "BAKING",
    defaultUnit: "kg",
    shelfLifeDays: 365,
    storageType: "PANTRY",
    avgPricePerUnit: 2.2,
    cuisineTags: ["AMERICAN", "FRENCH", "ITALIAN", "OTHER"],
    flavorTags: { sweet: 1, spicy: 0, umami: 1, acidic: 0, rich: 2, light: 6 },
    description:
      "Versatile wheat flour for cakes, cookies, sauces, and everyday doughs.",
  },
  {
    name: "Bread flour",
    category: "BAKING",
    defaultUnit: "kg",
    shelfLifeDays: 365,
    storageType: "PANTRY",
    avgPricePerUnit: 2.6,
    cuisineTags: ["AMERICAN", "ITALIAN", "FRENCH"],
    flavorTags: { sweet: 1, spicy: 0, umami: 2, acidic: 0, rich: 3, light: 5 },
    description: "Higher protein flour for chewy crumb and strong gluten structure in bread.",
  },
  {
    name: "00 flour",
    category: "BAKING",
    defaultUnit: "kg",
    shelfLifeDays: 365,
    storageType: "PANTRY",
    avgPricePerUnit: 3.4,
    cuisineTags: ["ITALIAN"],
    flavorTags: { sweet: 1, spicy: 0, umami: 1, acidic: 0, rich: 2, light: 6 },
    description: "Finely milled Italian flour ideal for tender pizza dough and fresh pasta.",
  },
  {
    name: "Semolina flour",
    category: "BAKING",
    defaultUnit: "kg",
    shelfLifeDays: 540,
    storageType: "PANTRY",
    avgPricePerUnit: 3.0,
    cuisineTags: ["ITALIAN", "MEDITERRANEAN", "MIDDLE_EASTERN"],
    flavorTags: { sweet: 0, spicy: 0, umami: 2, acidic: 0, rich: 3, light: 5 },
    description: "Durum wheat with a sandy texture; classic for pasta, couscous-style dishes, and dusting.",
  },
  {
    name: "Masa harina",
    category: "BAKING",
    defaultUnit: "kg",
    shelfLifeDays: 365,
    storageType: "PANTRY",
    avgPricePerUnit: 4.2,
    cuisineTags: ["MEXICAN", "AMERICAN", "OTHER"],
    flavorTags: { sweet: 1, spicy: 0, umami: 3, acidic: 0, rich: 3, light: 4 },
    description: "Nixtamalized corn flour for tortillas, tamales, and masa-based staples.",
  },
  {
    name: "Cornstarch",
    category: "BAKING",
    defaultUnit: "kg",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 3.8,
    cuisineTags: ["CHINESE", "AMERICAN", "THAI"],
    flavorTags: { sweet: 0, spicy: 0, umami: 0, acidic: 0, rich: 1, light: 8 },
    description: "Pure starch for silky sauces, crisp coatings, and tender baked textures.",
  },
  {
    name: "Granulated sugar",
    category: "BAKING",
    defaultUnit: "kg",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 2.0,
    cuisineTags: ["AMERICAN", "FRENCH", "OTHER"],
    flavorTags: { sweet: 10, spicy: 0, umami: 0, acidic: 0, rich: 2, light: 6 },
    description: "Standard refined sucrose for baking, brines, and balancing savory dishes.",
  },
  {
    name: "Brown sugar (light)",
    category: "BAKING",
    defaultUnit: "kg",
    shelfLifeDays: 540,
    storageType: "PANTRY",
    avgPricePerUnit: 2.4,
    cuisineTags: ["AMERICAN", "CARIBBEAN"],
    flavorTags: { sweet: 9, spicy: 0, umami: 1, acidic: 0, rich: 5, light: 4 },
    description: "Molasses-kissed sugar for cookies, glazes, and deeper caramel notes.",
  },
  {
    name: "Powdered sugar",
    category: "BAKING",
    defaultUnit: "kg",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 3.2,
    cuisineTags: ["AMERICAN", "FRENCH"],
    flavorTags: { sweet: 10, spicy: 0, umami: 0, acidic: 0, rich: 2, light: 7 },
    description: "Finely ground sugar with starch; icings, dusting, and delicate finishes.",
  },
  {
    name: "Baking powder",
    category: "BAKING",
    defaultUnit: "g",
    shelfLifeDays: 365,
    storageType: "PANTRY",
    avgPricePerUnit: 0.022,
    cuisineTags: ["AMERICAN", "FRENCH", "OTHER"],
    flavorTags: { sweet: 0, spicy: 0, umami: 0, acidic: 1, rich: 0, light: 7 },
    description: "Double-acting leavener for quick breads, cakes, and batters.",
  },
  {
    name: "Baking soda",
    category: "BAKING",
    defaultUnit: "g",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 0.012,
    cuisineTags: ["AMERICAN", "OTHER"],
    flavorTags: { sweet: 0, spicy: 0, umami: 0, acidic: 2, rich: 0, light: 5 },
    description: "Alkaline leavener; pairs with acid for lift and aids browning.",
  },
  {
    name: "Active dry yeast",
    category: "BAKING",
    defaultUnit: "g",
    shelfLifeDays: 365,
    storageType: "PANTRY",
    avgPricePerUnit: 0.08,
    cuisineTags: ["FRENCH", "ITALIAN", "AMERICAN"],
    flavorTags: { sweet: 1, spicy: 0, umami: 4, acidic: 0, rich: 3, light: 4 },
    description: "Traditional yeast granules; proof before use for predictable fermentation.",
  },
  {
    name: "Instant yeast",
    category: "BAKING",
    defaultUnit: "g",
    shelfLifeDays: 540,
    storageType: "PANTRY",
    avgPricePerUnit: 0.09,
    cuisineTags: ["FRENCH", "ITALIAN", "AMERICAN"],
    flavorTags: { sweet: 1, spicy: 0, umami: 4, acidic: 0, rich: 3, light: 4 },
    description: "Fast-dissolving yeast for streamlined mixing and reliable rise.",
  },
  {
    name: "Vanilla extract",
    category: "BAKING",
    defaultUnit: "ml",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 0.045,
    cuisineTags: ["AMERICAN", "FRENCH"],
    flavorTags: { sweet: 4, spicy: 0, umami: 1, acidic: 0, rich: 6, light: 3 },
    description: "Aromatic extract from vanilla beans; desserts, custards, and subtle rounding.",
  },
  {
    name: "Cocoa powder (natural)",
    category: "BAKING",
    defaultUnit: "g",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 0.028,
    cuisineTags: ["AMERICAN", "FRENCH", "MEXICAN"],
    flavorTags: { sweet: 2, spicy: 0, umami: 2, acidic: 2, rich: 8, light: 2 },
    description: "Unsweetened chocolate solids for deep color and bittersweet backbone.",
  },
  {
    name: "Dark chocolate (baking)",
    category: "BAKING",
    defaultUnit: "g",
    shelfLifeDays: 540,
    storageType: "PANTRY",
    avgPricePerUnit: 0.032,
    cuisineTags: ["FRENCH", "ITALIAN", "AMERICAN"],
    flavorTags: { sweet: 4, spicy: 0, umami: 2, acidic: 2, rich: 9, light: 1 },
    description: "High-cacao chocolate for ganache, mousses, and intense desserts.",
  },
  {
    name: "Semi-sweet chocolate chips",
    category: "BAKING",
    defaultUnit: "g",
    shelfLifeDays: 540,
    storageType: "PANTRY",
    avgPricePerUnit: 0.026,
    cuisineTags: ["AMERICAN"],
    flavorTags: { sweet: 7, spicy: 0, umami: 1, acidic: 1, rich: 7, light: 2 },
    description: "Balanced sweet chocolate morsels for cookies, folds, and melts.",
  },
  {
    name: "Honey",
    category: "PANTRY_STAPLE",
    defaultUnit: "ml",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 0.012,
    cuisineTags: ["MIDDLE_EASTERN", "MEDITERRANEAN", "AMERICAN", "OTHER"],
    flavorTags: { sweet: 9, spicy: 0, umami: 1, acidic: 0, rich: 4, light: 4 },
    description: "Floral, viscous sweetener for glazes, dressings, and baking moisture.",
  },
  {
    name: "Maple syrup",
    category: "PANTRY_STAPLE",
    defaultUnit: "ml",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 0.018,
    cuisineTags: ["AMERICAN", "OTHER"],
    flavorTags: { sweet: 8, spicy: 0, umami: 1, acidic: 0, rich: 5, light: 4 },
    description: "Grade A maple for breakfast, roasting, and nuanced caramel sweetness.",
  },
  {
    name: "Molasses",
    category: "PANTRY_STAPLE",
    defaultUnit: "ml",
    shelfLifeDays: 540,
    storageType: "PANTRY",
    avgPricePerUnit: 0.008,
    cuisineTags: ["AMERICAN", "CARIBBEAN"],
    flavorTags: { sweet: 7, spicy: 0, umami: 3, acidic: 1, rich: 8, light: 1 },
    description: "Robust cane syrup for gingerbread, BBQ depth, and complex sweetness.",
  },
  {
    name: "Light corn syrup",
    category: "BAKING",
    defaultUnit: "ml",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 0.006,
    cuisineTags: ["AMERICAN"],
    flavorTags: { sweet: 9, spicy: 0, umami: 0, acidic: 0, rich: 3, light: 5 },
    description: "Invert-friendly syrup for candy sheen, pecan pie set, and smooth textures.",
  },
  {
    name: "Unflavored gelatin (powder)",
    category: "BAKING",
    defaultUnit: "g",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 0.12,
    cuisineTags: ["FRENCH", "AMERICAN", "OTHER"],
    flavorTags: { sweet: 0, spicy: 0, umami: 1, acidic: 0, rich: 2, light: 6 },
    description: "Collagen-based gelling agent for panna cotta, aspic, and stable mousses.",
  },
  {
    name: "Kosher salt",
    category: "PANTRY_STAPLE",
    defaultUnit: "g",
    shelfLifeDays: 1825,
    storageType: "PANTRY",
    avgPricePerUnit: 0.004,
    cuisineTags: ["AMERICAN", "FRENCH", "ITALIAN", "OTHER"],
    flavorTags: { sweet: 0, spicy: 0, umami: 2, acidic: 0, rich: 1, light: 5 },
    description: "Large-crystal salt for seasoning by hand, brines, and finishing control.",
  },
  {
    name: "Cornmeal (medium grind)",
    category: "GRAIN",
    defaultUnit: "kg",
    shelfLifeDays: 365,
    storageType: "PANTRY",
    avgPricePerUnit: 2.8,
    cuisineTags: ["AMERICAN", "MEXICAN", "ITALIAN"],
    flavorTags: { sweet: 1, spicy: 0, umami: 2, acidic: 0, rich: 3, light: 5 },
    description: "Ground corn for cornbread, polenta-style sides, and crunchy dredging.",
  },
  {
    name: "Cream of tartar",
    category: "BAKING",
    defaultUnit: "g",
    shelfLifeDays: 1095,
    storageType: "PANTRY",
    avgPricePerUnit: 0.05,
    cuisineTags: ["AMERICAN", "FRENCH"],
    flavorTags: { sweet: 0, spicy: 0, umami: 0, acidic: 6, rich: 0, light: 5 },
    description: "Potassium bitartrate for stabilizing meringues and activating baking soda.",
  },
  {
    name: "Instant espresso powder",
    category: "BAKING",
    defaultUnit: "g",
    shelfLifeDays: 540,
    storageType: "PANTRY",
    avgPricePerUnit: 0.09,
    cuisineTags: ["ITALIAN", "AMERICAN"],
    flavorTags: { sweet: 1, spicy: 0, umami: 4, acidic: 3, rich: 7, light: 2 },
    description: "Concentrated coffee for chocolate amplification and tiramisu-style depth.",
  },
];
