export const produce = [
  // Alliums
  {
    name: "Yellow Onion",
    category: "PRODUCE",
    defaultUnit: "count",
    shelfLifeDays: 30,
    storageType: "PANTRY",
    avgPricePerUnit: 0.75,
    cuisineTags: ["FRENCH", "ITALIAN", "MEXICAN", "MEDITERRANEAN", "AMERICAN"],
    flavorTags: { sweet: 4, spicy: 1, umami: 3, acidic: 0, rich: 2, light: 3 },
    description: "Foundation aromatic for virtually all cuisines",
  },
  {
    name: "Red Onion",
    category: "PRODUCE",
    defaultUnit: "count",
    shelfLifeDays: 21,
    storageType: "PANTRY",
    avgPricePerUnit: 0.85,
    cuisineTags: ["MEXICAN", "MEDITERRANEAN", "AMERICAN", "OTHER"],
    flavorTags: { sweet: 5, spicy: 2, umami: 2, acidic: 3, rich: 1, light: 4 },
    description: "Milder bite; ideal raw in salads, tacos, and sandwiches",
  },
  {
    name: "White Onion",
    category: "PRODUCE",
    defaultUnit: "count",
    shelfLifeDays: 28,
    storageType: "PANTRY",
    avgPricePerUnit: 0.7,
    cuisineTags: ["MEXICAN", "AMERICAN", "OTHER"],
    flavorTags: { sweet: 3, spicy: 4, umami: 2, acidic: 1, rich: 1, light: 3 },
    description: "Sharper profile; classic for Mexican salsas and quick pickles",
  },
  {
    name: "Shallot",
    category: "PRODUCE",
    defaultUnit: "count",
    shelfLifeDays: 21,
    storageType: "PANTRY",
    avgPricePerUnit: 0.45,
    cuisineTags: ["FRENCH", "ITALIAN", "MEDITERRANEAN"],
    flavorTags: { sweet: 5, spicy: 2, umami: 4, acidic: 2, rich: 3, light: 4 },
    description: "Delicate onion-garlic note for sauces, vinaigrettes, and pan sauces",
  },
  {
    name: "Leek",
    category: "PRODUCE",
    defaultUnit: "count",
    shelfLifeDays: 10,
    storageType: "FRIDGE",
    avgPricePerUnit: 1.89,
    cuisineTags: ["FRENCH", "ITALIAN", "MEDITERRANEAN"],
    flavorTags: { sweet: 5, spicy: 1, umami: 3, acidic: 0, rich: 2, light: 5 },
    description: "Mild allium for soups, braises, and potato-leek classics",
  },
  {
    name: "Scallion",
    category: "PRODUCE",
    defaultUnit: "count",
    shelfLifeDays: 7,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.99,
    cuisineTags: ["MEXICAN", "JAPANESE", "AMERICAN", "OTHER"],
    flavorTags: { sweet: 3, spicy: 2, umami: 2, acidic: 1, rich: 1, light: 7 },
    description: "Fresh garnish and stir-fry finish; white and green parts differ in intensity",
  },
  {
    name: "Garlic",
    category: "PRODUCE",
    defaultUnit: "count",
    shelfLifeDays: 90,
    storageType: "PANTRY",
    avgPricePerUnit: 0.55,
    cuisineTags: ["FRENCH", "ITALIAN", "MEXICAN", "MEDITERRANEAN", "JAPANESE", "AMERICAN"],
    flavorTags: { sweet: 2, spicy: 6, umami: 5, acidic: 1, rich: 4, light: 2 },
    description: "Essential aromatic; roasts mellow and sweetens dramatically",
  },
  {
    name: "Chives",
    category: "PRODUCE",
    defaultUnit: "count",
    shelfLifeDays: 5,
    storageType: "FRIDGE",
    avgPricePerUnit: 2.49,
    cuisineTags: ["FRENCH", "DELI", "AMERICAN"],
    flavorTags: { sweet: 2, spicy: 3, umami: 2, acidic: 1, rich: 1, light: 8 },
    description: "Mild onion herb for fines herbes, eggs, and compound butters",
  },
  // Nightshades — tomatoes & peppers
  {
    name: "Roma Tomato",
    category: "PRODUCE",
    defaultUnit: "count",
    shelfLifeDays: 5,
    storageType: "COUNTER",
    avgPricePerUnit: 0.5,
    cuisineTags: ["ITALIAN", "MEXICAN", "MEDITERRANEAN", "AMERICAN"],
    flavorTags: { sweet: 5, spicy: 0, umami: 4, acidic: 6, rich: 2, light: 5 },
    description: "Plum type; dense flesh for sauces, paste, and slow cooking",
  },
  {
    name: "Cherry Tomato",
    category: "PRODUCE",
    defaultUnit: "count",
    shelfLifeDays: 5,
    storageType: "FRIDGE",
    avgPricePerUnit: 3.99,
    cuisineTags: ["ITALIAN", "MEDITERRANEAN", "AMERICAN"],
    flavorTags: { sweet: 7, spicy: 0, umami: 3, acidic: 5, rich: 2, light: 6 },
    description: "Snackable and salad-ready; blister or roast for concentrated sweetness",
  },
  {
    name: "Beefsteak Tomato",
    category: "PRODUCE",
    defaultUnit: "count",
    shelfLifeDays: 4,
    storageType: "COUNTER",
    avgPricePerUnit: 1.25,
    cuisineTags: ["ITALIAN", "AMERICAN", "DELI"],
    flavorTags: { sweet: 6, spicy: 0, umami: 4, acidic: 5, rich: 3, light: 5 },
    description: "Large slicing tomato for burgers, caprese, and thick sandwiches",
  },
  {
    name: "Red Bell Pepper",
    category: "PRODUCE",
    defaultUnit: "count",
    shelfLifeDays: 10,
    storageType: "FRIDGE",
    avgPricePerUnit: 1.29,
    cuisineTags: ["MEXICAN", "MEDITERRANEAN", "ITALIAN", "AMERICAN"],
    flavorTags: { sweet: 8, spicy: 0, umami: 2, acidic: 2, rich: 2, light: 6 },
    description: "Ripest bell; sweetest for roasting, romesco, and fajitas",
  },
  {
    name: "Green Bell Pepper",
    category: "PRODUCE",
    defaultUnit: "count",
    shelfLifeDays: 12,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.99,
    cuisineTags: ["MEXICAN", "AMERICAN", "OTHER"],
    flavorTags: { sweet: 3, spicy: 1, umami: 2, acidic: 3, rich: 2, light: 6 },
    description: "Vegetal and slightly bitter; classic in Cajun trinity and stir-fries",
  },
  {
    name: "Jalapeño",
    category: "PRODUCE",
    defaultUnit: "count",
    shelfLifeDays: 14,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.35,
    cuisineTags: ["MEXICAN", "AMERICAN"],
    flavorTags: { sweet: 2, spicy: 6, umami: 2, acidic: 2, rich: 2, light: 5 },
    description: "Moderate heat pepper for salsas, nachos, and pickled rings",
  },
  {
    name: "Serrano Pepper",
    category: "PRODUCE",
    defaultUnit: "count",
    shelfLifeDays: 14,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.4,
    cuisineTags: ["MEXICAN", "AMERICAN"],
    flavorTags: { sweet: 2, spicy: 8, umami: 2, acidic: 2, rich: 2, light: 5 },
    description: "Brighter heat than jalapeño; mince for pico and aguachile",
  },
  {
    name: "Habanero Pepper",
    category: "PRODUCE",
    defaultUnit: "count",
    shelfLifeDays: 10,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.65,
    cuisineTags: ["MEXICAN", "OTHER"],
    flavorTags: { sweet: 6, spicy: 10, umami: 2, acidic: 3, rich: 3, light: 4 },
    description: "Fiery tropical fruitiness; use sparingly in hot sauces and marinades",
  },
  {
    name: "Poblano Pepper",
    category: "PRODUCE",
    defaultUnit: "count",
    shelfLifeDays: 10,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.85,
    cuisineTags: ["MEXICAN", "AMERICAN"],
    flavorTags: { sweet: 4, spicy: 4, umami: 3, acidic: 2, rich: 3, light: 5 },
    description: "Mild to medium; roast for rajas, chiles rellenos, and mole bases",
  },
  {
    name: "Eggplant",
    category: "PRODUCE",
    defaultUnit: "count",
    shelfLifeDays: 5,
    storageType: "FRIDGE",
    avgPricePerUnit: 1.49,
    cuisineTags: ["ITALIAN", "MEDITERRANEAN", "FRENCH", "OTHER"],
    flavorTags: { sweet: 3, spicy: 0, umami: 4, acidic: 2, rich: 5, light: 4 },
    description: "Spongy flesh that absorbs fat and sauce; grill, fry, or braise",
  },
  {
    name: "Russet Potato",
    category: "PRODUCE",
    defaultUnit: "count",
    shelfLifeDays: 45,
    storageType: "PANTRY",
    avgPricePerUnit: 0.65,
    cuisineTags: ["AMERICAN", "FRENCH", "OTHER"],
    flavorTags: { sweet: 2, spicy: 0, umami: 3, acidic: 0, rich: 3, light: 4 },
    description: "Starchy baker; ideal mashed, fried, and oven-crisped skins",
  },
  {
    name: "Yukon Gold Potato",
    category: "PRODUCE",
    defaultUnit: "count",
    shelfLifeDays: 35,
    storageType: "PANTRY",
    avgPricePerUnit: 0.95,
    cuisineTags: ["FRENCH", "ITALIAN", "AMERICAN"],
    flavorTags: { sweet: 3, spicy: 0, umami: 3, acidic: 0, rich: 4, light: 4 },
    description: "Buttery waxy texture; holds shape in gratins and smashes creamy",
  },
  {
    name: "Fingerling Potato",
    category: "PRODUCE",
    defaultUnit: "count",
    shelfLifeDays: 21,
    storageType: "PANTRY",
    avgPricePerUnit: 2.49,
    cuisineTags: ["FRENCH", "AMERICAN", "ITALIAN"],
    flavorTags: { sweet: 4, spicy: 0, umami: 3, acidic: 0, rich: 4, light: 5 },
    description: "Small elongated tubers; roast whole with herbs and olive oil",
  },
  {
    name: "Sweet Potato",
    category: "PRODUCE",
    defaultUnit: "count",
    shelfLifeDays: 21,
    storageType: "PANTRY",
    avgPricePerUnit: 1.1,
    cuisineTags: ["AMERICAN", "OTHER", "MEXICAN"],
    flavorTags: { sweet: 8, spicy: 1, umami: 2, acidic: 1, rich: 4, light: 4 },
    description: "Orange-fleshed staple; bakes, fries, and purees with warm spices",
  },
  // Leafy greens & cabbage
  {
    name: "Spinach",
    category: "PRODUCE",
    defaultUnit: "count",
    shelfLifeDays: 5,
    storageType: "FRIDGE",
    avgPricePerUnit: 2.29,
    cuisineTags: ["FRENCH", "ITALIAN", "MEDITERRANEAN", "AMERICAN"],
    flavorTags: { sweet: 2, spicy: 0, umami: 3, acidic: 2, rich: 2, light: 7 },
    description: "Tender leaves for wilting, smoothies, and classic creamed sides",
  },
  {
    name: "Kale",
    category: "PRODUCE",
    defaultUnit: "count",
    shelfLifeDays: 7,
    storageType: "FRIDGE",
    avgPricePerUnit: 2.49,
    cuisineTags: ["AMERICAN", "ITALIAN", "MEDITERRANEAN"],
    flavorTags: { sweet: 2, spicy: 1, umami: 3, acidic: 2, rich: 3, light: 6 },
    description: "Hearty green; massage for salads or crisp as chips",
  },
  {
    name: "Arugula",
    category: "PRODUCE",
    defaultUnit: "count",
    shelfLifeDays: 4,
    storageType: "FRIDGE",
    avgPricePerUnit: 3.49,
    cuisineTags: ["ITALIAN", "FRENCH", "MEDITERRANEAN", "AMERICAN"],
    flavorTags: { sweet: 1, spicy: 4, umami: 2, acidic: 3, rich: 2, light: 8 },
    description: "Peppery salad green; pairs with lemon, parmesan, and prosciutto",
  },
  {
    name: "Romaine Lettuce",
    category: "PRODUCE",
    defaultUnit: "count",
    shelfLifeDays: 7,
    storageType: "FRIDGE",
    avgPricePerUnit: 1.99,
    cuisineTags: ["AMERICAN", "ITALIAN", "DELI"],
    flavorTags: { sweet: 2, spicy: 1, umami: 1, acidic: 2, rich: 1, light: 9 },
    description: "Crisp hearts for Caesar, wedges, and grilled lettuce",
  },
  {
    name: "Butter Lettuce",
    category: "PRODUCE",
    defaultUnit: "count",
    shelfLifeDays: 5,
    storageType: "FRIDGE",
    avgPricePerUnit: 2.29,
    cuisineTags: ["FRENCH", "AMERICAN"],
    flavorTags: { sweet: 3, spicy: 0, umami: 1, acidic: 1, rich: 2, light: 9 },
    description: "Soft cups for delicate salads and butter lettuce wraps",
  },
  {
    name: "Swiss Chard",
    category: "PRODUCE",
    defaultUnit: "count",
    shelfLifeDays: 5,
    storageType: "FRIDGE",
    avgPricePerUnit: 2.79,
    cuisineTags: ["MEDITERRANEAN", "FRENCH", "AMERICAN"],
    flavorTags: { sweet: 3, spicy: 1, umami: 3, acidic: 2, rich: 3, light: 6 },
    description: "Stems and leaves both usable; braise stems, wilt greens",
  },
  {
    name: "Green Cabbage",
    category: "PRODUCE",
    defaultUnit: "count",
    shelfLifeDays: 14,
    storageType: "FRIDGE",
    avgPricePerUnit: 1.29,
    cuisineTags: ["DELI", "AMERICAN", "OTHER", "JAPANESE"],
    flavorTags: { sweet: 3, spicy: 1, umami: 2, acidic: 2, rich: 2, light: 6 },
    description: "Slaw, kraut, and stir-fry workhorse; holds crunch when raw",
  },
  {
    name: "Red Cabbage",
    category: "PRODUCE",
    defaultUnit: "count",
    shelfLifeDays: 14,
    storageType: "FRIDGE",
    avgPricePerUnit: 1.49,
    cuisineTags: ["DELI", "FRENCH", "OTHER"],
    flavorTags: { sweet: 3, spicy: 1, umami: 2, acidic: 3, rich: 2, light: 6 },
    description: "Vivid color for pickles, braised sides, and winter salads",
  },
  {
    name: "Napa Cabbage",
    category: "PRODUCE",
    defaultUnit: "count",
    shelfLifeDays: 7,
    storageType: "FRIDGE",
    avgPricePerUnit: 2.19,
    cuisineTags: ["JAPANESE", "OTHER", "AMERICAN"],
    flavorTags: { sweet: 4, spicy: 0, umami: 3, acidic: 2, rich: 2, light: 7 },
    description: "Crisp-ribbed Asian cabbage for kimchi, hot pot, and quick pickles",
  },
  // Cruciferous
  {
    name: "Broccoli",
    category: "PRODUCE",
    defaultUnit: "count",
    shelfLifeDays: 5,
    storageType: "FRIDGE",
    avgPricePerUnit: 2.49,
    cuisineTags: ["ITALIAN", "AMERICAN", "JAPANESE", "OTHER"],
    flavorTags: { sweet: 2, spicy: 1, umami: 4, acidic: 2, rich: 3, light: 6 },
    description: "Florets and stems edible; roast hard for caramelized edges",
  },
  {
    name: "Cauliflower",
    category: "PRODUCE",
    defaultUnit: "count",
    shelfLifeDays: 7,
    storageType: "FRIDGE",
    avgPricePerUnit: 3.49,
    cuisineTags: ["ITALIAN", "MEDITERRANEAN", "AMERICAN", "OTHER"],
    flavorTags: { sweet: 3, spicy: 1, umami: 3, acidic: 1, rich: 3, light: 6 },
    description: "Neutral canvas for roasting, rice substitutes, and purees",
  },
  {
    name: "Brussels Sprouts",
    category: "PRODUCE",
    defaultUnit: "count",
    shelfLifeDays: 10,
    storageType: "FRIDGE",
    avgPricePerUnit: 3.99,
    cuisineTags: ["FRENCH", "AMERICAN", "OTHER"],
    flavorTags: { sweet: 4, spicy: 2, umami: 4, acidic: 2, rich: 4, light: 5 },
    description: "Halve and roast or shred raw; benefits from fat and high heat",
  },
  // Root & stalk
  {
    name: "Carrot",
    category: "PRODUCE",
    defaultUnit: "count",
    shelfLifeDays: 21,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.89,
    cuisineTags: ["FRENCH", "ITALIAN", "MEXICAN", "AMERICAN", "JAPANESE"],
    flavorTags: { sweet: 6, spicy: 0, umami: 2, acidic: 1, rich: 2, light: 5 },
    description: "Mirepoix staple; roasts concentrate sugars",
  },
  {
    name: "Celery",
    category: "PRODUCE",
    defaultUnit: "count",
    shelfLifeDays: 14,
    storageType: "FRIDGE",
    avgPricePerUnit: 1.99,
    cuisineTags: ["AMERICAN", "FRENCH", "ITALIAN", "DELI"],
    flavorTags: { sweet: 1, spicy: 1, umami: 2, acidic: 2, rich: 1, light: 8 },
    description: "Aromatic backbone for stocks, stuffing, and crudités",
  },
  {
    name: "Beet",
    category: "PRODUCE",
    defaultUnit: "count",
    shelfLifeDays: 14,
    storageType: "FRIDGE",
    avgPricePerUnit: 1.29,
    cuisineTags: ["FRENCH", "MEDITERRANEAN", "OTHER"],
    flavorTags: { sweet: 7, spicy: 0, umami: 3, acidic: 2, rich: 4, light: 4 },
    description: "Earthy root; roast, pickle, or juice; stains handled boards",
  },
  {
    name: "Turnip",
    category: "PRODUCE",
    defaultUnit: "count",
    shelfLifeDays: 14,
    storageType: "FRIDGE",
    avgPricePerUnit: 1.19,
    cuisineTags: ["FRENCH", "AMERICAN", "OTHER"],
    flavorTags: { sweet: 3, spicy: 2, umami: 3, acidic: 2, rich: 2, light: 6 },
    description: "Peppery root and edible greens; mash with potatoes or braise",
  },
  {
    name: "Parsnip",
    category: "PRODUCE",
    defaultUnit: "count",
    shelfLifeDays: 21,
    storageType: "FRIDGE",
    avgPricePerUnit: 1.99,
    cuisineTags: ["FRENCH", "AMERICAN", "OTHER"],
    flavorTags: { sweet: 7, spicy: 1, umami: 3, acidic: 1, rich: 4, light: 4 },
    description: "Sweet white root; roasts and purees like a winter carrot",
  },
  {
    name: "Radish",
    category: "PRODUCE",
    defaultUnit: "count",
    shelfLifeDays: 10,
    storageType: "FRIDGE",
    avgPricePerUnit: 1.49,
    cuisineTags: ["FRENCH", "MEXICAN", "JAPANESE", "AMERICAN"],
    flavorTags: { sweet: 2, spicy: 5, umami: 1, acidic: 3, rich: 1, light: 8 },
    description: "Crisp peppery globes; pickle, shave, or serve with butter and salt",
  },
  {
    name: "Daikon Radish",
    category: "PRODUCE",
    defaultUnit: "count",
    shelfLifeDays: 14,
    storageType: "FRIDGE",
    avgPricePerUnit: 2.29,
    cuisineTags: ["JAPANESE", "OTHER"],
    flavorTags: { sweet: 3, spicy: 3, umami: 2, acidic: 2, rich: 1, light: 7 },
    description: "Mild long radish for pickles, oden, and grated garnish",
  },
  {
    name: "Fennel Bulb",
    category: "PRODUCE",
    defaultUnit: "count",
    shelfLifeDays: 7,
    storageType: "FRIDGE",
    avgPricePerUnit: 2.99,
    cuisineTags: ["ITALIAN", "FRENCH", "MEDITERRANEAN"],
    flavorTags: { sweet: 5, spicy: 2, umami: 2, acidic: 2, rich: 2, light: 7 },
    description: "Licorice-anise crunch; shave raw or caramelize in braises",
  },
  {
    name: "Ginger Root",
    category: "PRODUCE",
    defaultUnit: "count",
    shelfLifeDays: 21,
    storageType: "FRIDGE",
    avgPricePerUnit: 3.99,
    cuisineTags: ["JAPANESE", "OTHER", "AMERICAN"],
    flavorTags: { sweet: 2, spicy: 7, umami: 3, acidic: 2, rich: 3, light: 5 },
    description: "Pungent rhizome for stir-fries, teas, marinades, and baking",
  },
  // Squash
  {
    name: "Zucchini",
    category: "PRODUCE",
    defaultUnit: "count",
    shelfLifeDays: 5,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.99,
    cuisineTags: ["ITALIAN", "FRENCH", "MEDITERRANEAN", "MEXICAN"],
    flavorTags: { sweet: 3, spicy: 0, umami: 2, acidic: 1, rich: 2, light: 7 },
    description: "Summer squash; grill, spiralize, or bake into quick breads",
  },
  {
    name: "Butternut Squash",
    category: "PRODUCE",
    defaultUnit: "count",
    shelfLifeDays: 60,
    storageType: "PANTRY",
    avgPricePerUnit: 2.49,
    cuisineTags: ["AMERICAN", "ITALIAN", "OTHER"],
    flavorTags: { sweet: 7, spicy: 1, umami: 3, acidic: 1, rich: 5, light: 3 },
    description: "Dense orange flesh for soups, ravioli filling, and roasting",
  },
  {
    name: "Acorn Squash",
    category: "PRODUCE",
    defaultUnit: "count",
    shelfLifeDays: 45,
    storageType: "PANTRY",
    avgPricePerUnit: 1.99,
    cuisineTags: ["AMERICAN", "OTHER"],
    flavorTags: { sweet: 6, spicy: 1, umami: 2, acidic: 1, rich: 4, light: 4 },
    description: "Small winter squash; halve and roast with maple or brown sugar",
  },
  {
    name: "Spaghetti Squash",
    category: "PRODUCE",
    defaultUnit: "count",
    shelfLifeDays: 30,
    storageType: "PANTRY",
    avgPricePerUnit: 2.29,
    cuisineTags: ["AMERICAN", "ITALIAN"],
    flavorTags: { sweet: 4, spicy: 0, umami: 2, acidic: 1, rich: 2, light: 6 },
    description: "Strand-like flesh after baking; low-carb pasta alternative",
  },
  // Fruiting vegetables
  {
    name: "Avocado",
    category: "PRODUCE",
    defaultUnit: "count",
    shelfLifeDays: 5,
    storageType: "COUNTER",
    avgPricePerUnit: 1.5,
    cuisineTags: ["MEXICAN", "AMERICAN", "OTHER"],
    flavorTags: { sweet: 2, spicy: 0, umami: 3, acidic: 1, rich: 9, light: 3 },
    description: "Ripen at room temp; move to fridge when soft for guacamole and toast",
  },
  {
    name: "Corn",
    category: "PRODUCE",
    defaultUnit: "count",
    shelfLifeDays: 3,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.65,
    cuisineTags: ["MEXICAN", "AMERICAN", "OTHER"],
    flavorTags: { sweet: 8, spicy: 0, umami: 2, acidic: 0, rich: 3, light: 5 },
    description: "Sweet ears; grill in husks or strip for succotash and salsas",
  },
  {
    name: "Cucumber",
    category: "PRODUCE",
    defaultUnit: "count",
    shelfLifeDays: 7,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.79,
    cuisineTags: ["MEDITERRANEAN", "DELI", "AMERICAN", "OTHER"],
    flavorTags: { sweet: 2, spicy: 0, umami: 1, acidic: 2, rich: 1, light: 9 },
    description: "Cool crunch for salads, pickles, and tzatziki",
  },
  {
    name: "Artichoke",
    category: "PRODUCE",
    defaultUnit: "count",
    shelfLifeDays: 5,
    storageType: "FRIDGE",
    avgPricePerUnit: 3.49,
    cuisineTags: ["ITALIAN", "FRENCH", "MEDITERRANEAN", "AMERICAN"],
    flavorTags: { sweet: 3, spicy: 0, umami: 4, acidic: 2, rich: 3, light: 5 },
    description: "Steamed or grilled; scrape leaves and savor the heart",
  },
  // Mushrooms
  {
    name: "Button Mushroom",
    category: "PRODUCE",
    defaultUnit: "count",
    shelfLifeDays: 5,
    storageType: "FRIDGE",
    avgPricePerUnit: 2.49,
    cuisineTags: ["FRENCH", "ITALIAN", "AMERICAN", "OTHER"],
    flavorTags: { sweet: 2, spicy: 0, umami: 6, acidic: 1, rich: 4, light: 5 },
    description: "Mild cultivated cap; slice for pizza, duxelles, and soups",
  },
  {
    name: "Cremini Mushroom",
    category: "PRODUCE",
    defaultUnit: "count",
    shelfLifeDays: 5,
    storageType: "FRIDGE",
    avgPricePerUnit: 2.99,
    cuisineTags: ["ITALIAN", "FRENCH", "AMERICAN"],
    flavorTags: { sweet: 2, spicy: 0, umami: 7, acidic: 1, rich: 5, light: 4 },
    description: "Baby portobello depth; upgrade from white buttons in sauces",
  },
  {
    name: "Shiitake Mushroom",
    category: "PRODUCE",
    defaultUnit: "count",
    shelfLifeDays: 7,
    storageType: "FRIDGE",
    avgPricePerUnit: 4.99,
    cuisineTags: ["JAPANESE", "OTHER", "AMERICAN"],
    flavorTags: { sweet: 2, spicy: 0, umami: 8, acidic: 1, rich: 6, light: 4 },
    description: "Smoky umami caps; dried form intensifies broths",
  },
  {
    name: "Oyster Mushroom",
    category: "PRODUCE",
    defaultUnit: "count",
    shelfLifeDays: 5,
    storageType: "FRIDGE",
    avgPricePerUnit: 5.49,
    cuisineTags: ["FRENCH", "OTHER", "AMERICAN"],
    flavorTags: { sweet: 3, spicy: 0, umami: 6, acidic: 1, rich: 4, light: 6 },
    description: "Delicate clusters; tear and sauté for vegan scallop texture",
  },
  {
    name: "Portobello Mushroom",
    category: "PRODUCE",
    defaultUnit: "count",
    shelfLifeDays: 5,
    storageType: "FRIDGE",
    avgPricePerUnit: 3.99,
    cuisineTags: ["ITALIAN", "AMERICAN", "OTHER"],
    flavorTags: { sweet: 2, spicy: 0, umami: 8, acidic: 1, rich: 6, light: 3 },
    description: "Large cap for grilling; meaty vegetarian burger substitute",
  },
  {
    name: "Porcini Mushroom (Dried)",
    category: "PRODUCE",
    defaultUnit: "count",
    shelfLifeDays: 365,
    storageType: "PANTRY",
    avgPricePerUnit: 12.99,
    cuisineTags: ["ITALIAN", "FRENCH", "MEDITERRANEAN"],
    flavorTags: { sweet: 2, spicy: 0, umami: 10, acidic: 1, rich: 7, light: 3 },
    description: "Rehydrate for risotto and ragù; soaking liquid is liquid gold",
  },
  // Fruits — citrus & orchard
  {
    name: "Lemon",
    category: "PRODUCE",
    defaultUnit: "count",
    shelfLifeDays: 14,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.55,
    cuisineTags: ["FRENCH", "ITALIAN", "MEDITERRANEAN", "AMERICAN", "MEXICAN"],
    flavorTags: { sweet: 1, spicy: 0, umami: 1, acidic: 10, rich: 2, light: 8 },
    description: "Acid and zest for dressings, fish, and preservation",
  },
  {
    name: "Lime",
    category: "PRODUCE",
    defaultUnit: "count",
    shelfLifeDays: 14,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.45,
    cuisineTags: ["MEXICAN", "OTHER", "AMERICAN"],
    flavorTags: { sweet: 1, spicy: 1, umami: 1, acidic: 9, rich: 2, light: 8 },
    description: "Key for ceviche, margaritas, and Southeast Asian balance",
  },
  {
    name: "Orange",
    category: "PRODUCE",
    defaultUnit: "count",
    shelfLifeDays: 14,
    storageType: "COUNTER",
    avgPricePerUnit: 0.75,
    cuisineTags: ["MEDITERRANEAN", "FRENCH", "AMERICAN", "OTHER"],
    flavorTags: { sweet: 8, spicy: 0, umami: 1, acidic: 5, rich: 2, light: 6 },
    description: "Juice, zest, and segments for sauces, salads, and duck",
  },
  {
    name: "Apple",
    category: "PRODUCE",
    defaultUnit: "count",
    shelfLifeDays: 30,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.85,
    cuisineTags: ["AMERICAN", "FRENCH", "OTHER", "DELI"],
    flavorTags: { sweet: 7, spicy: 0, umami: 1, acidic: 4, rich: 2, light: 6 },
    description: "Sweet-tart range; bake, sauce, or pair with pork and cheese",
  },
  {
    name: "Pear",
    category: "PRODUCE",
    defaultUnit: "count",
    shelfLifeDays: 5,
    storageType: "FRIDGE",
    avgPricePerUnit: 1.25,
    cuisineTags: ["FRENCH", "ITALIAN", "AMERICAN"],
    flavorTags: { sweet: 8, spicy: 0, umami: 1, acidic: 2, rich: 3, light: 6 },
    description: "Ripen from firm to juicy; poach, salad, or cheese board",
  },
  {
    name: "Banana",
    category: "PRODUCE",
    defaultUnit: "count",
    shelfLifeDays: 5,
    storageType: "COUNTER",
    avgPricePerUnit: 0.35,
    cuisineTags: ["AMERICAN", "OTHER"],
    flavorTags: { sweet: 9, spicy: 0, umami: 1, acidic: 1, rich: 3, light: 5 },
    description: "Spotty for baking; freeze for smoothies and nice cream",
  },
  {
    name: "Strawberry",
    category: "PRODUCE",
    defaultUnit: "count",
    shelfLifeDays: 4,
    storageType: "FRIDGE",
    avgPricePerUnit: 4.99,
    cuisineTags: ["FRENCH", "AMERICAN", "ITALIAN", "OTHER"],
    flavorTags: { sweet: 8, spicy: 0, umami: 1, acidic: 4, rich: 2, light: 7 },
    description: "Peak-season only for full perfume; macerate or reduce for sauces",
  },
  {
    name: "Blueberry",
    category: "PRODUCE",
    defaultUnit: "count",
    shelfLifeDays: 7,
    storageType: "FRIDGE",
    avgPricePerUnit: 5.49,
    cuisineTags: ["AMERICAN", "OTHER"],
    flavorTags: { sweet: 7, spicy: 0, umami: 1, acidic: 3, rich: 2, light: 7 },
    description: "Bursting berries for muffins, compotes, and savory gastriques",
  },
  {
    name: "Raspberry",
    category: "PRODUCE",
    defaultUnit: "count",
    shelfLifeDays: 3,
    storageType: "FRIDGE",
    avgPricePerUnit: 5.99,
    cuisineTags: ["FRENCH", "AMERICAN", "ITALIAN"],
    flavorTags: { sweet: 7, spicy: 0, umami: 1, acidic: 6, rich: 2, light: 7 },
    description: "Fragile drupelets; fold into creams or plate as dessert garnish",
  },
  // Tropical
  {
    name: "Mango",
    category: "PRODUCE",
    defaultUnit: "count",
    shelfLifeDays: 5,
    storageType: "COUNTER",
    avgPricePerUnit: 1.99,
    cuisineTags: ["MEXICAN", "OTHER", "AMERICAN"],
    flavorTags: { sweet: 9, spicy: 0, umami: 2, acidic: 3, rich: 4, light: 5 },
    description: "Tropical stone fruit for salsas, lassis, and sticky rice",
  },
  {
    name: "Pineapple",
    category: "PRODUCE",
    defaultUnit: "count",
    shelfLifeDays: 5,
    storageType: "COUNTER",
    avgPricePerUnit: 3.99,
    cuisineTags: ["MEXICAN", "OTHER", "AMERICAN"],
    flavorTags: { sweet: 9, spicy: 0, umami: 2, acidic: 6, rich: 2, light: 6 },
    description: "Enzyme-rich for marinades; grill rings or juice for drinks",
  },
  {
    name: "Coconut",
    category: "PRODUCE",
    defaultUnit: "count",
    shelfLifeDays: 14,
    storageType: "COUNTER",
    avgPricePerUnit: 2.99,
    cuisineTags: ["OTHER", "AMERICAN", "MEXICAN"],
    flavorTags: { sweet: 5, spicy: 0, umami: 2, acidic: 1, rich: 7, light: 4 },
    description: "Water, meat, and milk from one fruit; toast flakes for crunch",
  },
];
