/**
 * Seed data: protein ingredients (chef ERP).
 * Prices: avgPricePerUnit is per gram for weighted items; per count for eggs.
 */

export const proteins = [
  // ─── Poultry ───
  {
    name: "Chicken Breast",
    category: "PROTEIN",
    defaultUnit: "g",
    shelfLifeDays: 3,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.011,
    cuisineTags: ["FRENCH", "ITALIAN", "AMERICAN", "MEXICAN", "MEDITERRANEAN"],
    flavorTags: { sweet: 0, spicy: 0, umami: 4, acidic: 0, rich: 3, light: 5 },
    description: "Versatile lean protein, quick-cooking",
  },
  {
    name: "Chicken Thigh",
    category: "PROTEIN",
    defaultUnit: "g",
    shelfLifeDays: 3,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.009,
    cuisineTags: ["FRENCH", "ITALIAN", "AMERICAN", "MEXICAN", "MEDITERRANEAN", "OTHER"],
    flavorTags: { sweet: 0, spicy: 0, umami: 5, acidic: 0, rich: 6, light: 3 },
    description: "Dark meat, forgiving and juicy when braised or roasted",
  },
  {
    name: "Whole Chicken",
    category: "PROTEIN",
    defaultUnit: "g",
    shelfLifeDays: 3,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.0065,
    cuisineTags: ["FRENCH", "ITALIAN", "AMERICAN", "MEDITERRANEAN", "OTHER"],
    flavorTags: { sweet: 0, spicy: 0, umami: 5, acidic: 0, rich: 5, light: 4 },
    description: "Roast whole or break down for multiple uses",
  },
  {
    name: "Chicken Wings",
    category: "PROTEIN",
    defaultUnit: "g",
    shelfLifeDays: 3,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.008,
    cuisineTags: ["AMERICAN", "MEXICAN", "OTHER"],
    flavorTags: { sweet: 1, spicy: 4, umami: 4, acidic: 1, rich: 5, light: 2 },
    description: "Skin-on; ideal for frying, grilling, or glazing",
  },
  {
    name: "Duck Breast",
    category: "PROTEIN",
    defaultUnit: "g",
    shelfLifeDays: 3,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.028,
    cuisineTags: ["FRENCH", "MEDITERRANEAN", "OTHER"],
    flavorTags: { sweet: 1, spicy: 0, umami: 7, acidic: 0, rich: 9, light: 1 },
    description: "Render skin crisp, serve medium-rare",
  },
  {
    name: "Duck Leg",
    category: "PROTEIN",
    defaultUnit: "g",
    shelfLifeDays: 3,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.018,
    cuisineTags: ["FRENCH", "MEDITERRANEAN", "OTHER"],
    flavorTags: { sweet: 0, spicy: 0, umami: 7, acidic: 0, rich: 8, light: 2 },
    description: "Confit, braise, or slow-roast",
  },
  {
    name: "Turkey Breast",
    category: "PROTEIN",
    defaultUnit: "g",
    shelfLifeDays: 3,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.01,
    cuisineTags: ["AMERICAN", "DELI", "OTHER"],
    flavorTags: { sweet: 0, spicy: 0, umami: 4, acidic: 0, rich: 3, light: 5 },
    description: "Lean roast or slice for sandwiches",
  },
  {
    name: "Ground Turkey",
    category: "PROTEIN",
    defaultUnit: "g",
    shelfLifeDays: 2,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.009,
    cuisineTags: ["AMERICAN", "ITALIAN", "MEXICAN", "OTHER"],
    flavorTags: { sweet: 0, spicy: 0, umami: 4, acidic: 0, rich: 3, light: 6 },
    description: "Lean swap for ground beef in many recipes",
  },
  {
    name: "Quail",
    category: "PROTEIN",
    defaultUnit: "g",
    shelfLifeDays: 3,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.035,
    cuisineTags: ["FRENCH", "MEDITERRANEAN", "OTHER"],
    flavorTags: { sweet: 0, spicy: 0, umami: 6, acidic: 0, rich: 6, light: 4 },
    description: "Small game bird; quick roast or grill whole",
  },

  // ─── Beef ───
  {
    name: "Ribeye Steak",
    category: "PROTEIN",
    defaultUnit: "g",
    shelfLifeDays: 4,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.038,
    cuisineTags: ["AMERICAN", "FRENCH", "ITALIAN", "OTHER"],
    flavorTags: { sweet: 0, spicy: 0, umami: 8, acidic: 0, rich: 9, light: 1 },
    description: "Well-marbled steak for high-heat sear",
  },
  {
    name: "Strip Steak",
    category: "PROTEIN",
    defaultUnit: "g",
    shelfLifeDays: 4,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.032,
    cuisineTags: ["AMERICAN", "FRENCH", "OTHER"],
    flavorTags: { sweet: 0, spicy: 0, umami: 8, acidic: 0, rich: 7, light: 2 },
    description: "NY strip; firm texture, bold beef flavor",
  },
  {
    name: "Beef Tenderloin",
    category: "PROTEIN",
    defaultUnit: "g",
    shelfLifeDays: 4,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.055,
    cuisineTags: ["FRENCH", "AMERICAN", "OTHER"],
    flavorTags: { sweet: 0, spicy: 0, umami: 7, acidic: 0, rich: 6, light: 4 },
    description: "Filet mignon cut; very tender, milder beef note",
  },
  {
    name: "Chuck Roast",
    category: "PROTEIN",
    defaultUnit: "g",
    shelfLifeDays: 4,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.012,
    cuisineTags: ["AMERICAN", "FRENCH", "ITALIAN", "OTHER"],
    flavorTags: { sweet: 0, spicy: 0, umami: 8, acidic: 0, rich: 7, light: 2 },
    description: "Economical cut for pot roast and long braises",
  },
  {
    name: "Beef Short Ribs",
    category: "PROTEIN",
    defaultUnit: "g",
    shelfLifeDays: 4,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.022,
    cuisineTags: ["AMERICAN", "FRENCH", "JAPANESE", "OTHER"],
    flavorTags: { sweet: 0, spicy: 1, umami: 9, acidic: 0, rich: 9, light: 1 },
    description: "Bone-in; rich collagen for glossy sauces",
  },
  {
    name: "Ground Beef",
    category: "PROTEIN",
    defaultUnit: "g",
    shelfLifeDays: 2,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.011,
    cuisineTags: ["AMERICAN", "ITALIAN", "MEXICAN", "OTHER"],
    flavorTags: { sweet: 0, spicy: 0, umami: 7, acidic: 0, rich: 6, light: 3 },
    description: "80/20 typical; burgers, meatballs, ragu",
  },
  {
    name: "Beef Brisket",
    category: "PROTEIN",
    defaultUnit: "g",
    shelfLifeDays: 4,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.015,
    cuisineTags: ["AMERICAN", "DELI", "OTHER"],
    flavorTags: { sweet: 0, spicy: 2, umami: 8, acidic: 0, rich: 8, light: 1 },
    description: "Low and slow smoke or braise",
  },
  {
    name: "Oxtail",
    category: "PROTEIN",
    defaultUnit: "g",
    shelfLifeDays: 3,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.018,
    cuisineTags: ["FRENCH", "ITALIAN", "AMERICAN", "OTHER"],
    flavorTags: { sweet: 0, spicy: 0, umami: 9, acidic: 0, rich: 9, light: 1 },
    description: "Gelatin-rich; soups, stews, and braises",
  },
  {
    name: "Bone Marrow",
    category: "PROTEIN",
    defaultUnit: "g",
    shelfLifeDays: 3,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.02,
    cuisineTags: ["FRENCH", "ITALIAN", "OTHER"],
    flavorTags: { sweet: 0, spicy: 0, umami: 8, acidic: 0, rich: 10, light: 0 },
    description: "Roast bones; spread on toast or enrich sauces",
  },
  {
    name: "Flank Steak",
    category: "PROTEIN",
    defaultUnit: "g",
    shelfLifeDays: 4,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.024,
    cuisineTags: ["AMERICAN", "MEXICAN", "OTHER"],
    flavorTags: { sweet: 0, spicy: 1, umami: 7, acidic: 1, rich: 5, light: 4 },
    description: "Slice thin across the grain for fajitas or salad",
  },
  {
    name: "Skirt Steak",
    category: "PROTEIN",
    defaultUnit: "g",
    shelfLifeDays: 4,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.026,
    cuisineTags: ["MEXICAN", "AMERICAN", "OTHER"],
    flavorTags: { sweet: 0, spicy: 2, umami: 7, acidic: 1, rich: 6, light: 3 },
    description: "Classic carne asada cut; marinate and sear hot",
  },

  // ─── Pork ───
  {
    name: "Pork Chop",
    category: "PROTEIN",
    defaultUnit: "g",
    shelfLifeDays: 4,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.01,
    cuisineTags: ["AMERICAN", "FRENCH", "ITALIAN", "OTHER"],
    flavorTags: { sweet: 1, spicy: 0, umami: 5, acidic: 0, rich: 5, light: 4 },
    description: "Bone-in or boneless; pan-sear or grill",
  },
  {
    name: "Pork Belly",
    category: "PROTEIN",
    defaultUnit: "g",
    shelfLifeDays: 4,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.012,
    cuisineTags: ["JAPANESE", "AMERICAN", "OTHER"],
    flavorTags: { sweet: 1, spicy: 1, umami: 7, acidic: 0, rich: 10, light: 0 },
    description: "Crispy skin roasts, braises, and confit",
  },
  {
    name: "Pork Shoulder",
    category: "PROTEIN",
    defaultUnit: "g",
    shelfLifeDays: 4,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.0075,
    cuisineTags: ["MEXICAN", "AMERICAN", "OTHER"],
    flavorTags: { sweet: 0, spicy: 2, umami: 6, acidic: 1, rich: 6, light: 3 },
    description: "Boston butt; pulled pork and long cooks",
  },
  {
    name: "Pork Loin",
    category: "PROTEIN",
    defaultUnit: "g",
    shelfLifeDays: 4,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.009,
    cuisineTags: ["AMERICAN", "FRENCH", "ITALIAN", "OTHER"],
    flavorTags: { sweet: 1, spicy: 0, umami: 5, acidic: 0, rich: 4, light: 5 },
    description: "Lean roast; careful not to overcook",
  },
  {
    name: "Bacon",
    category: "PROTEIN",
    defaultUnit: "g",
    shelfLifeDays: 14,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.018,
    cuisineTags: ["AMERICAN", "DELI", "OTHER"],
    flavorTags: { sweet: 2, spicy: 1, umami: 7, acidic: 0, rich: 8, light: 1 },
    description: "Smoked streaky; render for fat and crisp bits",
  },
  {
    name: "Pancetta",
    category: "PROTEIN",
    defaultUnit: "g",
    shelfLifeDays: 21,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.028,
    cuisineTags: ["ITALIAN", "OTHER"],
    flavorTags: { sweet: 0, spicy: 1, umami: 8, acidic: 0, rich: 8, light: 2 },
    description: "Italian cured pork belly; dice for soffritto",
  },
  {
    name: "Guanciale",
    category: "PROTEIN",
    defaultUnit: "g",
    shelfLifeDays: 30,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.032,
    cuisineTags: ["ITALIAN", "OTHER"],
    flavorTags: { sweet: 0, spicy: 1, umami: 9, acidic: 0, rich: 9, light: 1 },
    description: "Cured jowl; traditional carbonara and amatriciana",
  },
  {
    name: "Prosciutto",
    category: "PROTEIN",
    defaultUnit: "g",
    shelfLifeDays: 90,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.055,
    cuisineTags: ["ITALIAN", "OTHER"],
    flavorTags: { sweet: 1, spicy: 0, umami: 9, acidic: 0, rich: 7, light: 4 },
    description: "Dry-cured ham; paper-thin slices",
  },
  {
    name: "Ham",
    category: "PROTEIN",
    defaultUnit: "g",
    shelfLifeDays: 10,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.012,
    cuisineTags: ["AMERICAN", "DELI", "FRENCH", "OTHER"],
    flavorTags: { sweet: 3, spicy: 0, umami: 6, acidic: 0, rich: 5, light: 4 },
    description: "Cooked or smoked leg; slices and dices",
  },
  {
    name: "Chorizo",
    category: "PROTEIN",
    defaultUnit: "g",
    shelfLifeDays: 14,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.016,
    cuisineTags: ["MEXICAN", "MEDITERRANEAN", "AMERICAN", "OTHER"],
    flavorTags: { sweet: 1, spicy: 7, umami: 7, acidic: 2, rich: 7, light: 2 },
    description: "Spiced sausage; fresh or cured depending on style",
  },
  {
    name: "Italian Sausage",
    category: "PROTEIN",
    defaultUnit: "g",
    shelfLifeDays: 3,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.011,
    cuisineTags: ["ITALIAN", "AMERICAN", "OTHER"],
    flavorTags: { sweet: 1, spicy: 3, umami: 6, acidic: 1, rich: 6, light: 3 },
    description: "Sweet or hot fennel sausage in links or bulk",
  },
  {
    name: "Bratwurst",
    category: "PROTEIN",
    defaultUnit: "g",
    shelfLifeDays: 4,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.012,
    cuisineTags: ["AMERICAN", "OTHER"],
    flavorTags: { sweet: 1, spicy: 2, umami: 6, acidic: 0, rich: 6, light: 3 },
    description: "German-style fresh sausage; grill or poach in beer",
  },

  // ─── Lamb ───
  {
    name: "Lamb Rack",
    category: "PROTEIN",
    defaultUnit: "g",
    shelfLifeDays: 4,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.042,
    cuisineTags: ["FRENCH", "MEDITERRANEAN", "OTHER"],
    flavorTags: { sweet: 0, spicy: 0, umami: 7, acidic: 0, rich: 8, light: 3 },
    description: "Frenched bones; roast medium-rare",
  },
  {
    name: "Lamb Shank",
    category: "PROTEIN",
    defaultUnit: "g",
    shelfLifeDays: 4,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.016,
    cuisineTags: ["FRENCH", "ITALIAN", "MEDITERRANEAN", "OTHER"],
    flavorTags: { sweet: 0, spicy: 1, umami: 8, acidic: 0, rich: 8, light: 2 },
    description: "Foreshank; braise until fork-tender",
  },
  {
    name: "Lamb Shoulder",
    category: "PROTEIN",
    defaultUnit: "g",
    shelfLifeDays: 4,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.014,
    cuisineTags: ["MEDITERRANEAN", "FRENCH", "OTHER"],
    flavorTags: { sweet: 0, spicy: 2, umami: 7, acidic: 0, rich: 7, light: 3 },
    description: "Roast low or braise; more fat and flavor than leg",
  },
  {
    name: "Ground Lamb",
    category: "PROTEIN",
    defaultUnit: "g",
    shelfLifeDays: 2,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.013,
    cuisineTags: ["MEDITERRANEAN", "MEXICAN", "OTHER"],
    flavorTags: { sweet: 0, spicy: 2, umami: 7, acidic: 0, rich: 6, light: 3 },
    description: "Kebabs, kofta, and spiced patties",
  },
  {
    name: "Lamb Chops",
    category: "PROTEIN",
    defaultUnit: "g",
    shelfLifeDays: 4,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.038,
    cuisineTags: ["FRENCH", "MEDITERRANEAN", "OTHER"],
    flavorTags: { sweet: 0, spicy: 0, umami: 7, acidic: 0, rich: 7, light: 4 },
    description: "Loin or rib chops; quick grill or pan-sear",
  },

  // ─── Seafood ───
  {
    name: "Salmon Fillet",
    category: "PROTEIN",
    defaultUnit: "g",
    shelfLifeDays: 2,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.024,
    cuisineTags: ["JAPANESE", "MEDITERRANEAN", "AMERICAN", "OTHER"],
    flavorTags: { sweet: 1, spicy: 0, umami: 6, acidic: 1, rich: 7, light: 4 },
    description: "Rich oily fish; sear, roast, or cure",
  },
  {
    name: "Shrimp",
    category: "PROTEIN",
    defaultUnit: "g",
    shelfLifeDays: 2,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.022,
    cuisineTags: ["JAPANESE", "MEXICAN", "MEDITERRANEAN", "AMERICAN", "OTHER"],
    flavorTags: { sweet: 2, spicy: 2, umami: 6, acidic: 1, rich: 4, light: 5 },
    description: "Peeled or shell-on; fast sauté or boil",
  },
  {
    name: "Sea Bass Fillet",
    category: "PROTEIN",
    defaultUnit: "g",
    shelfLifeDays: 2,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.032,
    cuisineTags: ["FRENCH", "MEDITERRANEAN", "JAPANESE", "OTHER"],
    flavorTags: { sweet: 1, spicy: 0, umami: 5, acidic: 1, rich: 4, light: 6 },
    description: "Delicate white fish; skin-on sear",
  },
  {
    name: "Cod Fillet",
    category: "PROTEIN",
    defaultUnit: "g",
    shelfLifeDays: 2,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.018,
    cuisineTags: ["FRENCH", "ITALIAN", "AMERICAN", "OTHER"],
    flavorTags: { sweet: 1, spicy: 0, umami: 4, acidic: 1, rich: 3, light: 7 },
    description: "Flaky mild fish; fish and chips or poach",
  },
  {
    name: "Tuna Steak",
    category: "PROTEIN",
    defaultUnit: "g",
    shelfLifeDays: 1,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.035,
    cuisineTags: ["JAPANESE", "MEDITERRANEAN", "AMERICAN", "OTHER"],
    flavorTags: { sweet: 0, spicy: 1, umami: 8, acidic: 0, rich: 6, light: 4 },
    description: "Sear rare to medium-rare; sushi-grade if raw",
  },
  {
    name: "Mussels",
    category: "PROTEIN",
    defaultUnit: "g",
    shelfLifeDays: 2,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.012,
    cuisineTags: ["FRENCH", "ITALIAN", "MEDITERRANEAN", "OTHER"],
    flavorTags: { sweet: 1, spicy: 1, umami: 8, acidic: 1, rich: 5, light: 5 },
    description: "Live shellfish; steam open with wine and aromatics",
  },
  {
    name: "Clams",
    category: "PROTEIN",
    defaultUnit: "g",
    shelfLifeDays: 2,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.014,
    cuisineTags: ["ITALIAN", "AMERICAN", "MEDITERRANEAN", "OTHER"],
    flavorTags: { sweet: 1, spicy: 0, umami: 7, acidic: 2, rich: 4, light: 6 },
    description: "Littlenecks or manila; pasta and chowders",
  },
  {
    name: "Scallops",
    category: "PROTEIN",
    defaultUnit: "g",
    shelfLifeDays: 2,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.045,
    cuisineTags: ["FRENCH", "JAPANESE", "AMERICAN", "OTHER"],
    flavorTags: { sweet: 3, spicy: 0, umami: 6, acidic: 0, rich: 5, light: 6 },
    description: "Dry sea scallops for best sear",
  },
  {
    name: "Octopus",
    category: "PROTEIN",
    defaultUnit: "g",
    shelfLifeDays: 2,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.028,
    cuisineTags: ["MEDITERRANEAN", "JAPANESE", "OTHER"],
    flavorTags: { sweet: 0, spicy: 1, umami: 7, acidic: 1, rich: 4, light: 5 },
    description: "Tenderize then grill or confit",
  },
  {
    name: "Squid",
    category: "PROTEIN",
    defaultUnit: "g",
    shelfLifeDays: 2,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.016,
    cuisineTags: ["MEDITERRANEAN", "JAPANESE", "OTHER"],
    flavorTags: { sweet: 0, spicy: 1, umami: 6, acidic: 1, rich: 3, light: 6 },
    description: "Calamari; very quick high-heat cook",
  },
  {
    name: "Lobster",
    category: "PROTEIN",
    defaultUnit: "g",
    shelfLifeDays: 1,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.065,
    cuisineTags: ["FRENCH", "AMERICAN", "OTHER"],
    flavorTags: { sweet: 3, spicy: 0, umami: 7, acidic: 1, rich: 7, light: 4 },
    description: "Live or cooked; tail and claw meat",
  },
  {
    name: "Crab Meat",
    category: "PROTEIN",
    defaultUnit: "g",
    shelfLifeDays: 2,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.08,
    cuisineTags: ["AMERICAN", "JAPANESE", "OTHER"],
    flavorTags: { sweet: 4, spicy: 0, umami: 7, acidic: 1, rich: 5, light: 5 },
    description: "Picked lump or claw; cakes and salads",
  },

  // ─── Other ───
  {
    name: "Eggs",
    category: "PROTEIN",
    defaultUnit: "count",
    shelfLifeDays: 21,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.32,
    cuisineTags: ["FRENCH", "ITALIAN", "AMERICAN", "JAPANESE", "OTHER"],
    flavorTags: { sweet: 0, spicy: 0, umami: 3, acidic: 0, rich: 5, light: 5 },
    description: "Large eggs; breakfast through baking and sauces",
  },
  {
    name: "Anchovies (Packed)",
    category: "PROTEIN",
    defaultUnit: "g",
    shelfLifeDays: 365,
    storageType: "PANTRY",
    avgPricePerUnit: 0.045,
    cuisineTags: ["ITALIAN", "FRENCH", "MEDITERRANEAN", "OTHER"],
    flavorTags: { sweet: 0, spicy: 0, umami: 10, acidic: 2, rich: 7, light: 3 },
    description: "Oil- or salt-packed fillets; depth for dressings and sauces",
  },
  {
    name: "Anchovies (Fresh Whole)",
    category: "PROTEIN",
    defaultUnit: "g",
    shelfLifeDays: 2,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.022,
    cuisineTags: ["MEDITERRANEAN", "ITALIAN", "OTHER"],
    flavorTags: { sweet: 0, spicy: 0, umami: 9, acidic: 2, rich: 6, light: 4 },
    description: "Whole fresh fish; grill, fry, or marinate; very perishable",
  },
  {
    name: "Pastrami",
    category: "PROTEIN",
    defaultUnit: "g",
    shelfLifeDays: 7,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.028,
    cuisineTags: ["DELI", "AMERICAN", "OTHER"],
    flavorTags: { sweet: 1, spicy: 4, umami: 8, acidic: 1, rich: 7, light: 2 },
    description: "Spiced smoked beef; thin slices for sandwiches",
  },
  {
    name: "Corned Beef",
    category: "PROTEIN",
    defaultUnit: "g",
    shelfLifeDays: 7,
    storageType: "FRIDGE",
    avgPricePerUnit: 0.018,
    cuisineTags: ["DELI", "AMERICAN", "OTHER"],
    flavorTags: { sweet: 0, spicy: 2, umami: 7, acidic: 1, rich: 6, light: 3 },
    description: "Brined brisket; simmer with cabbage or slice cold",
  },
];
