export type SpiceSeed = {
  name: string;
  category: "SPICE";
  defaultUnit: string;
  shelfLifeDays: number;
  storageType: "FRIDGE" | "FREEZER" | "PANTRY" | "COUNTER";
  avgPricePerUnit: number;
  cuisineTags: string[];
  flavorTags: {
    sweet: number;
    spicy: number;
    umami: number;
    acidic: number;
    rich: number;
    light: number;
  };
  description: string;
};

export const spices: SpiceSeed[] = [
  {
    name: "Black pepper (ground)",
    category: "SPICE",
    defaultUnit: "tsp",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 0.12,
    cuisineTags: ["ITALIAN", "FRENCH", "AMERICAN", "INDIAN", "OTHER"],
    flavorTags: { sweet: 0, spicy: 4, umami: 2, acidic: 0, rich: 2, light: 3 },
    description: "Pungent piperine heat and aroma; foundational seasoning worldwide.",
  },
  {
    name: "White pepper (ground)",
    category: "SPICE",
    defaultUnit: "tsp",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 0.14,
    cuisineTags: ["FRENCH", "OTHER"],
    flavorTags: { sweet: 0, spicy: 3, umami: 2, acidic: 0, rich: 2, light: 4 },
    description: "Earthy fermented pepper; white sauces, mash, and Asian soups without black specks.",
  },
  {
    name: "Kosher salt",
    category: "SPICE",
    defaultUnit: "tsp",
    shelfLifeDays: 1825,
    storageType: "PANTRY",
    avgPricePerUnit: 0.02,
    cuisineTags: ["AMERICAN", "DELI", "OTHER"],
    flavorTags: { sweet: 0, spicy: 0, umami: 3, acidic: 0, rich: 1, light: 2 },
    description: "Coarse flake salt for seasoning by hand, brines, and finishing.",
  },
  {
    name: "Sea salt (fine)",
    category: "SPICE",
    defaultUnit: "tsp",
    shelfLifeDays: 1825,
    storageType: "PANTRY",
    avgPricePerUnit: 0.025,
    cuisineTags: ["MEDITERRANEAN", "FRENCH", "OTHER"],
    flavorTags: { sweet: 0, spicy: 0, umami: 3, acidic: 0, rich: 1, light: 3 },
    description: "Mineral-forward crystalline salt for everyday cooking and baking.",
  },
  {
    name: "Fleur de sel",
    category: "SPICE",
    defaultUnit: "tsp",
    shelfLifeDays: 1825,
    storageType: "PANTRY",
    avgPricePerUnit: 0.45,
    cuisineTags: ["FRENCH", "OTHER"],
    flavorTags: { sweet: 0, spicy: 0, umami: 2, acidic: 0, rich: 2, light: 4 },
    description: "Delicate finishing salt with moisture; sprinkle on vegetables and chocolate.",
  },
  {
    name: "Red pepper flakes",
    category: "SPICE",
    defaultUnit: "tsp",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 0.08,
    cuisineTags: ["ITALIAN", "AMERICAN", "MEXICAN", "OTHER"],
    flavorTags: { sweet: 0, spicy: 8, umami: 2, acidic: 1, rich: 2, light: 2 },
    description: "Crushed dried chiles for pizza, pasta aglio e olio, and chili oil.",
  },
  {
    name: "Sweet paprika",
    category: "SPICE",
    defaultUnit: "tsp",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 0.1,
    cuisineTags: ["MEDITERRANEAN", "OTHER"],
    flavorTags: { sweet: 2, spicy: 1, umami: 2, acidic: 0, rich: 2, light: 4 },
    description: "Mild red pepper powder for color and subtle fruit in stews and rubs.",
  },
  {
    name: "Smoked paprika (pimentón)",
    category: "SPICE",
    defaultUnit: "tsp",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 0.12,
    cuisineTags: ["MEDITERRANEAN", "OTHER"],
    flavorTags: { sweet: 1, spicy: 2, umami: 5, acidic: 0, rich: 6, light: 2 },
    description: "Oak-smoked pepper; paella, chorizo flavor, and barbecue rubs.",
  },
  {
    name: "Cayenne pepper",
    category: "SPICE",
    defaultUnit: "tsp",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 0.09,
    cuisineTags: ["AMERICAN", "MEXICAN", "INDIAN", "OTHER"],
    flavorTags: { sweet: 0, spicy: 9, umami: 1, acidic: 0, rich: 1, light: 2 },
    description: "Pure heat powder; use sparingly in sauces, dry rubs, and chili.",
  },
  {
    name: "Herbes de Provence",
    category: "SPICE",
    defaultUnit: "tsp",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 0.15,
    cuisineTags: ["FRENCH", "MEDITERRANEAN", "OTHER"],
    flavorTags: { sweet: 1, spicy: 0, umami: 3, acidic: 1, rich: 3, light: 5 },
    description: "Dried blend of thyme, rosemary, marjoram; roast chicken and ratatouille.",
  },
  {
    name: "Quatre-épices",
    category: "SPICE",
    defaultUnit: "tsp",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 0.18,
    cuisineTags: ["FRENCH", "OTHER"],
    flavorTags: { sweet: 3, spicy: 1, umami: 3, acidic: 0, rich: 4, light: 2 },
    description: "Warm blend of pepper, clove, nutmeg, ginger; pâtés and winter stews.",
  },
  {
    name: "Nutmeg (ground)",
    category: "SPICE",
    defaultUnit: "tsp",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 0.22,
    cuisineTags: ["FRENCH", "ITALIAN", "AMERICAN", "INDIAN", "OTHER"],
    flavorTags: { sweet: 4, spicy: 1, umami: 2, acidic: 0, rich: 5, light: 2 },
    description: "Warm sweet spice for béchamel, eggnog, and spinach dishes.",
  },
  {
    name: "Saffron threads",
    category: "SPICE",
    defaultUnit: "tsp",
    shelfLifeDays: 1095,
    storageType: "PANTRY",
    avgPricePerUnit: 8.5,
    cuisineTags: ["MEDITERRANEAN", "MIDDLE_EASTERN", "INDIAN", "OTHER"],
    flavorTags: { sweet: 2, spicy: 0, umami: 4, acidic: 1, rich: 4, light: 4 },
    description: "Precious stigma for golden color and hay-like aroma; risotto and paella.",
  },
  {
    name: "Dried tarragon",
    category: "SPICE",
    defaultUnit: "tsp",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 0.2,
    cuisineTags: ["FRENCH", "OTHER"],
    flavorTags: { sweet: 1, spicy: 0, umami: 2, acidic: 2, rich: 2, light: 6 },
    description: "Anise-leaning herb; béarnaise, chicken, and vinegar reductions.",
  },
  {
    name: "Dried oregano",
    category: "SPICE",
    defaultUnit: "tsp",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 0.1,
    cuisineTags: ["ITALIAN", "MEXICAN", "MEDITERRANEAN", "AMERICAN", "OTHER"],
    flavorTags: { sweet: 0, spicy: 1, umami: 3, acidic: 2, rich: 2, light: 5 },
    description: "Robust mint-family herb; pizza sauce, Greek salad, and chili.",
  },
  {
    name: "Dried basil",
    category: "SPICE",
    defaultUnit: "tsp",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 0.12,
    cuisineTags: ["ITALIAN", "AMERICAN", "OTHER"],
    flavorTags: { sweet: 2, spicy: 0, umami: 2, acidic: 1, rich: 2, light: 6 },
    description: "Sweet aromatic leaf; tomato sauces when fresh basil is unavailable.",
  },
  {
    name: "Fennel seed",
    category: "SPICE",
    defaultUnit: "tsp",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 0.11,
    cuisineTags: ["ITALIAN", "MEDITERRANEAN", "INDIAN", "OTHER"],
    flavorTags: { sweet: 3, spicy: 0, umami: 2, acidic: 0, rich: 3, light: 5 },
    description: "Licorice-like whole seeds; sausage, porchetta, and Indian mukhwas.",
  },
  {
    name: "Anise seed",
    category: "SPICE",
    defaultUnit: "tsp",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 0.13,
    cuisineTags: ["MEXICAN", "MIDDLE_EASTERN", "OTHER"],
    flavorTags: { sweet: 5, spicy: 0, umami: 1, acidic: 0, rich: 2, light: 5 },
    description: "Sweet licorice aroma; cookies, pho broth, and Mexican moles.",
  },
  {
    name: "Ground cumin",
    category: "SPICE",
    defaultUnit: "tsp",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 0.09,
    cuisineTags: ["MEXICAN", "MIDDLE_EASTERN", "INDIAN", "AMERICAN", "OTHER"],
    flavorTags: { sweet: 0, spicy: 2, umami: 4, acidic: 1, rich: 3, light: 4 },
    description: "Earthy warm seed; tacos, hummus, and curry bases.",
  },
  {
    name: "Chili powder (blend)",
    category: "SPICE",
    defaultUnit: "tsp",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 0.08,
    cuisineTags: ["MEXICAN", "AMERICAN", "OTHER"],
    flavorTags: { sweet: 1, spicy: 5, umami: 3, acidic: 1, rich: 3, light: 3 },
    description: "Mixed chile and spices; chili con carne, rubs, and beans.",
  },
  {
    name: "Ancho chile powder",
    category: "SPICE",
    defaultUnit: "tsp",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 0.11,
    cuisineTags: ["MEXICAN", "AMERICAN", "OTHER"],
    flavorTags: { sweet: 3, spicy: 4, umami: 4, acidic: 2, rich: 4, light: 2 },
    description: "Mild fruity dried poblano; enchilada sauce and mole coloradito.",
  },
  {
    name: "Chipotle powder",
    category: "SPICE",
    defaultUnit: "tsp",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 0.12,
    cuisineTags: ["MEXICAN", "AMERICAN", "OTHER"],
    flavorTags: { sweet: 2, spicy: 6, umami: 5, acidic: 2, rich: 5, light: 1 },
    description: "Smoked jalapeño heat; adobo flavor in rubs, mayo, and beans.",
  },
  {
    name: "Mexican oregano (dried)",
    category: "SPICE",
    defaultUnit: "tsp",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 0.11,
    cuisineTags: ["MEXICAN", "AMERICAN", "OTHER"],
    flavorTags: { sweet: 0, spicy: 2, umami: 3, acidic: 3, rich: 2, light: 5 },
    description: "Grassier than Mediterranean oregano; pozole, salsas, and carnitas.",
  },
  {
    name: "Mexican cinnamon (canela)",
    category: "SPICE",
    defaultUnit: "tsp",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 0.14,
    cuisineTags: ["MEXICAN", "OTHER"],
    flavorTags: { sweet: 7, spicy: 1, umami: 1, acidic: 0, rich: 3, light: 3 },
    description: "Soft Ceylon-style bark; horchata, mole, and spiced chocolate.",
  },
  {
    name: "Ground coriander",
    category: "SPICE",
    defaultUnit: "tsp",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 0.08,
    cuisineTags: ["MEXICAN", "MIDDLE_EASTERN", "INDIAN", "OTHER"],
    flavorTags: { sweet: 2, spicy: 1, umami: 2, acidic: 2, rich: 2, light: 6 },
    description: "Citrusy seed; curry blends, carnitas, and pickling spice.",
  },
  {
    name: "Sumac",
    category: "SPICE",
    defaultUnit: "tsp",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 0.16,
    cuisineTags: ["MIDDLE_EASTERN", "MEDITERRANEAN", "OTHER"],
    flavorTags: { sweet: 1, spicy: 0, umami: 2, acidic: 8, rich: 1, light: 6 },
    description: "Tart purple berry powder; fattoush, kebabs, and yogurt dips.",
  },
  {
    name: "Za'atar blend",
    category: "SPICE",
    defaultUnit: "tsp",
    shelfLifeDays: 365,
    storageType: "PANTRY",
    avgPricePerUnit: 0.2,
    cuisineTags: ["MIDDLE_EASTERN", "MEDITERRANEAN", "OTHER"],
    flavorTags: { sweet: 1, spicy: 1, umami: 4, acidic: 3, rich: 3, light: 5 },
    description: "Thyme, sumac, sesame mix; manakish, labneh, and roast vegetables.",
  },
  {
    name: "Aleppo pepper (flakes)",
    category: "SPICE",
    defaultUnit: "tsp",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 0.17,
    cuisineTags: ["MIDDLE_EASTERN", "MEDITERRANEAN", "OTHER"],
    flavorTags: { sweet: 2, spicy: 4, umami: 3, acidic: 2, rich: 3, light: 4 },
    description: "Fruity mild heat with oil; kebabs, eggs, and muhammara.",
  },
  {
    name: "Ground turmeric",
    category: "SPICE",
    defaultUnit: "tsp",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 0.07,
    cuisineTags: ["INDIAN", "MIDDLE_EASTERN", "OTHER"],
    flavorTags: { sweet: 1, spicy: 2, umami: 2, acidic: 1, rich: 2, light: 5 },
    description: "Earthy golden rhizome; curry, golden milk, and rice tinting.",
  },
  {
    name: "Ground cardamom",
    category: "SPICE",
    defaultUnit: "tsp",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 0.35,
    cuisineTags: ["INDIAN", "MIDDLE_EASTERN", "OTHER"],
    flavorTags: { sweet: 4, spicy: 1, umami: 2, acidic: 1, rich: 3, light: 5 },
    description: "Floral resinous pod; chai, biryani, and Scandinavian baking.",
  },
  {
    name: "Chinese five spice",
    category: "SPICE",
    defaultUnit: "tsp",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 0.14,
    cuisineTags: ["OTHER"],
    flavorTags: { sweet: 4, spicy: 2, umami: 4, acidic: 1, rich: 4, light: 2 },
    description: "Star anise, clove, cinnamon, Sichuan pepper, fennel; braises and roast duck.",
  },
  {
    name: "Star anise (whole)",
    category: "SPICE",
    defaultUnit: "tsp",
    shelfLifeDays: 1095,
    storageType: "PANTRY",
    avgPricePerUnit: 0.25,
    cuisineTags: ["OTHER"],
    flavorTags: { sweet: 3, spicy: 1, umami: 3, acidic: 1, rich: 4, light: 3 },
    description: "Licorice-forward pod; pho, braised pork, and poached fruit.",
  },
  {
    name: "Sichuan peppercorn",
    category: "SPICE",
    defaultUnit: "tsp",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 0.28,
    cuisineTags: ["JAPANESE", "OTHER"],
    flavorTags: { sweet: 1, spicy: 3, umami: 3, acidic: 2, rich: 2, light: 4 },
    description: "Numbing citrusy hua jiao; mapo tofu and chili oil.",
  },
  {
    name: "Ginger (ground)",
    category: "SPICE",
    defaultUnit: "tsp",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 0.09,
    cuisineTags: ["INDIAN", "MIDDLE_EASTERN", "AMERICAN", "OTHER"],
    flavorTags: { sweet: 2, spicy: 4, umami: 2, acidic: 2, rich: 2, light: 4 },
    description: "Warm zingy rhizome powder; cookies, curry, and dry rubs.",
  },
  {
    name: "Wasabi powder",
    category: "SPICE",
    defaultUnit: "tsp",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 0.45,
    cuisineTags: ["JAPANESE", "OTHER"],
    flavorTags: { sweet: 0, spicy: 8, umami: 4, acidic: 2, rich: 1, light: 5 },
    description: "Horseradish-style heat when rehydrated; sushi and dressings.",
  },
  {
    name: "Shichimi togarashi",
    category: "SPICE",
    defaultUnit: "tsp",
    shelfLifeDays: 365,
    storageType: "PANTRY",
    avgPricePerUnit: 0.22,
    cuisineTags: ["JAPANESE", "OTHER"],
    flavorTags: { sweet: 1, spicy: 6, umami: 4, acidic: 2, rich: 2, light: 4 },
    description: "Seven-flavor chili blend with citrus peel and nori; noodles and grilled meat.",
  },
  {
    name: "Garlic powder",
    category: "SPICE",
    defaultUnit: "tsp",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 0.06,
    cuisineTags: ["ITALIAN", "MEXICAN", "AMERICAN", "OTHER"],
    flavorTags: { sweet: 1, spicy: 1, umami: 6, acidic: 1, rich: 3, light: 3 },
    description: "Concentrated allium; rubs, popcorn, and dry mixes.",
  },
  {
    name: "Onion powder",
    category: "SPICE",
    defaultUnit: "tsp",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 0.06,
    cuisineTags: ["AMERICAN", "DELI", "OTHER"],
    flavorTags: { sweet: 2, spicy: 0, umami: 5, acidic: 1, rich: 3, light: 4 },
    description: "Sweet savory backbone; burger blends, dip mixes, and soup bases.",
  },
  {
    name: "Mustard powder",
    category: "SPICE",
    defaultUnit: "tsp",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 0.08,
    cuisineTags: ["FRENCH", "AMERICAN", "DELI", "OTHER"],
    flavorTags: { sweet: 0, spicy: 5, umami: 3, acidic: 3, rich: 2, light: 4 },
    description: "Heat when mixed with liquid; deviled eggs, vinaigrettes, and rubs.",
  },
  {
    name: "Celery seed",
    category: "SPICE",
    defaultUnit: "tsp",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 0.1,
    cuisineTags: ["AMERICAN", "DELI", "OTHER"],
    flavorTags: { sweet: 0, spicy: 1, umami: 3, acidic: 2, rich: 2, light: 5 },
    description: "Concentrated celery note; coleslaw, pickles, and Old Bay style blends.",
  },
  {
    name: "Bay leaf (dried)",
    category: "SPICE",
    defaultUnit: "tsp",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 0.15,
    cuisineTags: ["FRENCH", "ITALIAN", "MEXICAN", "AMERICAN", "OTHER"],
    flavorTags: { sweet: 0, spicy: 0, umami: 3, acidic: 1, rich: 3, light: 4 },
    description: "Aromatic leaf for long simmers; stocks, beans, and braises.",
  },
  {
    name: "Cloves (ground)",
    category: "SPICE",
    defaultUnit: "tsp",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 0.2,
    cuisineTags: ["FRENCH", "INDIAN", "OTHER"],
    flavorTags: { sweet: 4, spicy: 3, umami: 2, acidic: 0, rich: 4, light: 2 },
    description: "Intense warm spice; mulled wine, ham glaze, and garam masala.",
  },
  {
    name: "Allspice (ground)",
    category: "SPICE",
    defaultUnit: "tsp",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 0.12,
    cuisineTags: ["MEXICAN", "AMERICAN", "OTHER"],
    flavorTags: { sweet: 4, spicy: 2, umami: 2, acidic: 1, rich: 3, light: 3 },
    description: "Jamaican pepper berry; jerk seasoning, pumpkin pie, and moles.",
  },
  {
    name: "Juniper berries (whole)",
    category: "SPICE",
    defaultUnit: "tsp",
    shelfLifeDays: 1095,
    storageType: "PANTRY",
    avgPricePerUnit: 0.24,
    cuisineTags: ["FRENCH", "OTHER"],
    flavorTags: { sweet: 1, spicy: 2, umami: 3, acidic: 4, rich: 2, light: 5 },
    description: "Piney resinous berry; sauerkraut, game, and gin flavor.",
  },
  {
    name: "Caraway seed",
    category: "SPICE",
    defaultUnit: "tsp",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 0.11,
    cuisineTags: ["DELI", "OTHER"],
    flavorTags: { sweet: 1, spicy: 1, umami: 2, acidic: 1, rich: 3, light: 5 },
    description: "Anise-cumin note; rye bread, sauerkraut, and cabbage.",
  },
  {
    name: "Dill seed",
    category: "SPICE",
    defaultUnit: "tsp",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 0.1,
    cuisineTags: ["DELI", "MEDITERRANEAN", "OTHER"],
    flavorTags: { sweet: 1, spicy: 0, umami: 2, acidic: 2, rich: 2, light: 6 },
    description: "Brighter than leaf dill; pickles, bread, and potato salads.",
  },
  {
    name: "Celery salt",
    category: "SPICE",
    defaultUnit: "tsp",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 0.07,
    cuisineTags: ["AMERICAN", "DELI", "OTHER"],
    flavorTags: { sweet: 0, spicy: 0, umami: 4, acidic: 1, rich: 2, light: 3 },
    description: "Salt with ground celery seed; Bloody Mary rim and Chicago-style hot dogs.",
  },
  {
    name: "Smoked salt",
    category: "SPICE",
    defaultUnit: "tsp",
    shelfLifeDays: 1095,
    storageType: "PANTRY",
    avgPricePerUnit: 0.2,
    cuisineTags: ["AMERICAN", "OTHER"],
    flavorTags: { sweet: 0, spicy: 0, umami: 5, acidic: 0, rich: 5, light: 2 },
    description: "Cold-smoked salt for finishing meat, eggs, and chocolate.",
  },
  {
    name: "Pink Himalayan salt",
    category: "SPICE",
    defaultUnit: "tsp",
    shelfLifeDays: 1825,
    storageType: "PANTRY",
    avgPricePerUnit: 0.03,
    cuisineTags: ["MIDDLE_EASTERN", "OTHER"],
    flavorTags: { sweet: 0, spicy: 0, umami: 2, acidic: 0, rich: 1, light: 3 },
    description: "Mineral-pink rock salt; grinders, curing, and roasting crusts.",
  },
  {
    name: "Poppy seed",
    category: "SPICE",
    defaultUnit: "tsp",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 0.11,
    cuisineTags: ["DELI", "OTHER"],
    flavorTags: { sweet: 2, spicy: 0, umami: 2, acidic: 1, rich: 3, light: 5 },
    description: "Tiny nutty crunch; bagels, lemon cake, and Eastern European pastries.",
  },
  {
    name: "Fenugreek seed (whole)",
    category: "SPICE",
    defaultUnit: "tsp",
    shelfLifeDays: 730,
    storageType: "PANTRY",
    avgPricePerUnit: 0.09,
    cuisineTags: ["INDIAN", "MIDDLE_EASTERN", "OTHER"],
    flavorTags: { sweet: 2, spicy: 1, umami: 5, acidic: 1, rich: 4, light: 3 },
    description: "Maple-curry aroma; dal tadka, pickles, and imitation maple syrup notes.",
  },
];
